### ISSUE TITLE
Website editor not work on HTTPS

### ISSUE THREAD

**Issue by shurshilov** [odoo/odoo#104597]
Impacted versions:
16

Steps to reproduce:
install website go to website click edit

Current behavior:
not loaded and give error
Mixed Content: The page at 'https://repo.site/web#action=585&cids=1&menu_id=446' was loaded over HTTPS, but requested an insecure frame 'http://repo.site/'. This request has been blocked; the content must be served over HTTPS.

Expected behavior:
open website editor

----------------------

**[Odoo (RDE) message]: It's a misconfiguration on your end, please see https://github.com/odoo/odoo/issues/104597#issuecomment-1496279435 and https://github.com/odoo/odoo/issues/104597#issuecomment-1505563744**

**Comment by netfxtech** [comment]
I am having the same issue. I thought it was something I was doing wrong but I’ve used the same traefik config successfully for years. 

web.base.url is set
web.base.url.freeze is set
No 3rd party modules 
All assets in viewer are loading https except base.url for some reason. 

I can make it work in Firefox if I disable the warning.

**Comment by shurshilov** [comment]
its fixed on nginx side loki this 
add_header 'Content-Security-Policy' 'upgrade-insecure-requests';
BUT i think problem that JS go to http instead https, may be bug

**Comment by netfxtech** [comment]
Yes, thank you for the suggestion. I could also go to http://127.0.0.1:8069 —- nginx or bypassing ssl term is a bandaid, it’s still a bug that should be fixed in my opinion.

**Comment by matzrm** [comment]
same here

**Comment by pixelfoundry-dev** [comment]
same here

**Comment by eperezsolla** [comment]
Is there a solution for apache?

**Comment by netfxtech** [comment]
I wish I knew exactly what the cause was. I have 11 odoo databases that I manage and I had this issue on 10 of them. No rhyme or reason that I could tell caused this. 

I think what I did was edit the website by adding some random image directly using the IP address and port like http://my.ip.ad.dress:8069

Then I would make sure my 

web.base.url: https://mydomain.com web.base.url.freeze: True

Soon afterwards it seemingly allowed me to start editing the website. 

I can’t recall which asset wasn’t loading correctly but I’m sure it could be found pretty quick and either prevented from loading or forced to load. Sorry, I wish I could be more help. It’s a really annoying issue that odoo doesn’t care enough about to fix.

**Comment by iox-ZKBLHT** [comment]
Same issue here with Apache. Any update or fixes yet?

**Comment by LeDistordu** [comment]
+1 here with Cloudflare > Odoo or Haproxy > Odoo

**Comment by rdeodoo** [comment]
Hello,

This issue raised my attention since it was linked in an [opw](https://www.odoo.com/web#id=3233056&cids=1&model=project.task&view_type=form).

You are all mentioning the `web.base.url`, but what is your website's domain set to? Basically, the domain will shadow the `web.base.url` almost everywhere / in every flow. In a nutshell, and some exception apart, the `web.base.url` is no more useful once website is installed.

In 16.0, the website app was completely refactored: it now displays your website in an iframe inside your web client. The web editor is then part of the web client itself and not bound to the website (iframe) anymore.

Reading the reported traceback from the initial post, it seems like this iframe is trying to load the HTTP version of your website, while you are on the HTTPS version of it (in the back end).

It shouldn't be the case: the URL of the iframe is supposed to be `/website/force/xx` which ends up loading the website **domain URL** (on top of other things).

First thing first: are you sure your website domain is correctly configures with `https`?

**Comment by netfxtech** [comment]
I always use web.base.url.freeze when I first install Odoo. That could be part of the issue. 

At least for me, it’s always coming down to a translation trying to load as http. I actually ran into this issue again this weekend. 

Start with a clean database without demo data. Install the contacts module and website at the same time. Go through the website configurator and when you get to the end you’ll understand what the issue is. The page will never load and you’ll see the loading image/processing spin forever. 

Yes I have SSL termination working perfectly. I always use the odoo/docker image.

**Comment by LeDistordu** [comment]
Hello,

I tried everything! Without report.url / web.base.url.freeze and with

Before v16 it worked like this:

Offloading with Haproxy like this:

(https) Haproxy > (http:8069) Odoo
report.url: http://0.0.0.0:8069
web.base.url: https://odoo.mydomain.com

Same problem with Cloudflare and the zerotrust tunnel! I also tested with "proxy_mode = True", it doesn't change anything, as if the option does nothing.

Now impossible to make it work, I have the impression that v16 does not support offloading!

**Comment by rdeodoo** [comment]
First of all, know that our own servers are running fine with multiple proxies in the request stack and since pretty much forever.
We thus know that regular well configured proxies will work fine.

In the cases reported here, this is because somewhere in one of your proxy there is something wrongly configured, making the client ultimately redirected from HTTPS to HTTP.

We were able to reproduce your issue in multiple ways (wrong `X-Forwarded-Proto` value ot not sent at all, `proxy_mode` not enabled..), here is an attempt at explaining how and why.

A typical case of such a wrong behavior will occur when your `X-Forwarded-Host`, `X-Forwarded-For`, `X-Forwarded-Proto` are not correctly configured as hinted in our doc: https://www.odoo.com/documentation/16.0/administration/install/deploy.html#id7
Without those properly configured, the Odoo server (werkzeug) will send a response with a redirect Location set to an absolute path which will be using `http` if the `X-Forwarded-Proto` is not passed correctly.
Indeed, werkzeug is converting the relative redirect to absolute ones (before [2.2](https://werkzeug.palletsprojects.com/en/2.2.x/wrappers/#werkzeug.wrappers.Response.autocorrect_location_header) which is the case for any odoo version up top now anyway) using the best scheme it manages to figure.
Since your proxy (eg nginx) did not correctly set that `X-Forwarded-Proto` header and is communicating in HTTP with your Odoo server (werkzeug), werkzeug response's location can only be sent back in HTTP since nothing is telling it to use HTTPS (incoming request is HTTP from nginx, and no `X-Forwarded-Proto` header).

One way to check if this might be the reason, is to force werkzeug to not convert relative redirect to absolute in the python code. You can do that with the following diff:

```diff
diff --git addons/website/controllers/main.py addons/website/controllers/main.py
index 66f58ad63882..633fc07849d6 100644
--- addons/website/controllers/main.py
+++ addons/website/controllers/main.py
@@ -142,9 +142,13 @@ class Website(Home):
             if domain_from != domain_to:
                 # redirect to correct domain for a correct routing map
                 url_to = werkzeug.urls.url_join(website.domain, '/website/force/%s?isredir=1&path=%s' % (website.id, path))
-                return request.redirect(url_to)
+                resp = request.redirect(url_to)
+                resp.autocorrect_location_header = False
+                return resp
         website._force()
-        return request.redirect(path)
+        resp = request.redirect(path)
+        resp.autocorrect_location_header = False
+        return resp
 
     @http.route(['/@/', '/@/<path:path>'], type='http', auth='public', website=True, sitemap=False, multilang=False)
     def client_action_redirect(self, path='', **kw):
```
The redirect should then be a relative one, not involving any scheme change.

Note that cloudflare, as per their documentation, is most likely correctly sending it and shouldn't be incriminated.

--------------------------------

The other possibility if that your [cloudflare SSL configuration](https://developers.cloudflare.com/ssl/origin-configuration/ssl-modes/) is not in `Full` mode, meaning that cloudflare is communicating with your nginx proxy in HTTP.
From there, the `X-Forwarded-Proto` sent from cloudflare to nginx is probably lost due to a lack of configuration (you are on your own if you selected that non "Full" configuration), since nginx now need to not forward the current scheme of the request (since it was in HTTP from cloudflare) but forward the already forwarded scheme.
So, basically, instead of nginx doing:
```
proxy_set_header X-Forwarded-Proto $scheme;
```
The `$scheme` part would need to be the `X-Forwarded-Proto` already sent by Cloudflare. And you probably want to only do that if you can recognize the incoming request as one from Cloudflare (based on the known IP of cloudflare, and keep using `$scheme` for the rest even if it shouldn't matter much).
Note that for debugging purpose, you might just force `$scheme` to `'https'`.

----------------------------

As a summary:
- There might be multiple proxies involved in the request before reaching the final Odoo server
- Each of those proxies need to be correctly configured, especially the `X-Forwarded-Proto` which is in charge of keeping track of the initial client request scheme.
- Proxies might communicate to other proxies in HTTP, meaning that themselves should correctly listen and forward the correct scheme: not especially the one from the request.
- Werkzeug will convert relative redirect to absolute one, using the best scheme he can find, this is why the `X-Forwarded-Proto` is so important

Courtesy of @odony for the in depth explanation. Hopefully I summarized it well enough for you guys to be able to debug what's going on.

**Comment by netfxtech** [comment]
Wow I really appreciate the time you took to respond to this. I’ll go through it line by line to try diagnosing this. 

Regarding cloudflare I’m not so confident. I am running in full mode and as you can see I haven’t changed the setting in 2 years. I have it forwarding to a cloudflare tunnel which config looks like this

- hostname: domain.com
   path: /websocket
   service: http://127.0.0.1:8072

- hostname: domain
   service: http://127.0.0.1:8069

![IMG_1598](https://user-images.githubusercontent.com/62037189/229868364-ab80c7d6-8a26-4fcd-9850-78f2d7473d1c.png)

**Comment by netfxtech** [comment]
If you have time to look at issue #104947 you might find some parallels. They are probably somewhat related.

**Comment by LeDistordu** [comment]
Why Nginx on Odoo serveur ?

Cloudflare can serve directly to Odoo with tunnel

![cloudfared](https://user-images.githubusercontent.com/7805145/229873931-fa79f98b-3826-4fdc-ab45-c3c48ace3b19.png)

We have been working like this since Odoo 10

The conversation being as direct as possible, I don't understand

**Comment by netfxtech** [comment]
Not sure if your comment is directed towards me… I do not have Nginx running. Pure from Cloudflare to Odoo :)

**Comment by Julien00859** [comment]
See also: https://github.com/odoo/odoo/issues/104947#issuecomment-1505552791

**Comment by Etren** [comment]
When I encountered this problem, I set "`web.base.url`" to "`https://mydomain.com`", "`web.base.url.freeze`" to "`True`", and finally added "`proxy_redirect http://$scheme://;`" in the site settings of nginx, and then I could edit the website page normally.

**Comment by hussainaljamri** [comment]
We are also having this issue. We have odoo enterprise deployed on AWS ECS and ALB with SSL/TLS termination. Odoo is responding to the request for the page that would be the editor with a 303, with a response header of `Location: http://example.com`. It should return https in that header, but for some reason it is not. I have web.base.url set to https and the website domain set to https.

**Comment by knipknap** [comment]
I have been trying to debug this for hours, but found no solution for me yet. I tried everything suggested here, too:

- Set web.base.url to https://mydomain.com
- Set web.base.url.freeze
- Configured proxy headers (in Traefik in my case):
    ```
    - traefik.http.middlewares.upgrade-insecure-requests.headers.customrequestheaders.X-Forwarded-Proto=https,wss
    - traefik.http.middlewares.upgrade-insecure-requests.headers.customRequestHeaders.Upgrade-Insecure-Requests=1
    - traefik.http.middlewares.upgrade-insecure-requests.headers.customRequestHeaders.Upgrade=websocket
    - traefik.http.middlewares.upgrade-insecure-requests.headers.customRequestHeaders.Connection=Upgrade
    - traefik.http.middlewares.upgrade-insecure-requests.headers.hostsproxyheaders=websocket,Upgrade
    ```
- I validated that those headers are actually being sent to the browser (they are).

Nevertheless, the browser still tries to respond using HTTP, rather than HTTPS. I see this in Chrome's debug console:

`Mixed Content: The page at 'https://shop.mysite.com/web#action=289&cids=1&menu_id=175' was loaded over HTTPS, but requested an insecure frame 'http://shop.mysite.com/'. This request has been blocked; the content must be served over HTTPS.`

I honestly also don't understand the explanation from @rdeodoo - to me this looks like an issue with the frontend, not the backend, so I don't see why X-Forwarded-Proto would make a difference.

Any other ideas?

**Comment by sbouillon** [comment]
> I have been trying to debug this for hours, and finally found a solution for Traefik. What finally worked:
> 
> * Set web.base.url to https://mydomain.com
> * Configured proxy headers (in Traefik in my case):
>   ```
>   - traefik.http.middlewares.upgrade-insecure-requests.headers.customrequestheaders.X-Forwarded-Proto=https,wss
>   - traefik.http.middlewares.upgrade-insecure-requests.headers.customresponseheaders.Content-Security-Policy=upgrade-insecure-requests
>   ```
> 
> Without this, the browser still tries to respond using HTTP, rather than HTTPS. I see this in Chrome's debug console:
> 
> `Mixed Content: The page at 'https://shop.mysite.com/web#action=289&cids=1&menu_id=175' was loaded over HTTPS, but requested an insecure frame 'http://shop.mysite.com/'. This request has been blocked; the content must be served over HTTPS.`
> 
> I honestly also don't understand the explanation from @rdeodoo though - to me this looks like an issue with the frontend, not the backend, so I don't see why X-Forwarded-Proto should make a difference. And setting the custom response header as shown above seems like a workaround, but not like a solution that addresses the root cause.
> 
> But in any case, it works for me now.
> 
> Note that there is one more place that I noticed fails even with the above workaround: The stripe integration is unable to automatically register the webhook, because it tries to register an HTTP endpoint in Stripe. So I had to follow the docs to enable it manually.

Are you using a cloudflare tunnel and then sending it to Traefik? If so, are you using a config file on the server or configuring it through Cloudflare’s website?

I can post my settings either way because I have it working. I’m not knowledgeable enough regarding the issue to argue why this or that doesn’t work, but I know what settings work for me.

**Comment by nassoor** [comment]
For those using Cloudflare Tunnel, add this header using Transform Rules > Modify Request Header >

set dynamic | X-Forwarded-Host | http.host

**Comment by sbouillon** [comment]
> For those using Cloudflare Tunnel, add this header using Transform Rules > Modify Request Header >
> 
> set dynamic | X-Forwarded-Host | http.host

You are awesome! Thank you!!

**Comment by rriemann** [comment]
Hello!

I ran today into the same issue with odoo 16 installed from Docker Hub (no odoo.conf or so in use). It is a fresh installation. I have Caddy in front. Caddy sets the following automatically:

- It sets or augments the [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) header field.
- It sets the [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) header field.
- It sets the [X-Forwarded-Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host) header field.

Source: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults


However, I still see the error in the Firefox developer console:

> Blocked loading mixed active content "http://odoo.my-domain.host/"

**Comment by matthewlenz** [comment]
We have this same issue with Odoo 17 and GCP LB.  All the X-Fowarded-* headers are set correctly.  Not using nginx on the server just GCB LB -> Odoo.

**Comment by AquaMCU** [comment]
I have the same issue. Since it is only happening when you open the website and click on editor, I suspect there is something wrong with the URL of the IFRAME. In the image you can clearly see, that the non secure page is requested by odoo. I tripplechecked my web base. That is correct, so I suspect in the below linkify is something fishy going on. 

What do y'all think?

            const href = !/^https?:\/\//i.test(url) ? "http://" + encodeURI(url) : encodeURI(url);

function linkify(text, attrs) {
        attrs = attrs || {};
        if (attrs.target === undefined) {
            attrs.target = "_blank";
        }
        if (attrs.target === "_blank") {
            attrs.rel = "noreferrer noopener";
        }
        attrs = Object.keys(attrs || {}).map((key)=>{
            const value = attrs[key];
            return `${key}="${escape(value)}"`;
        }
        ).join(" ");
        let curIndex = 0;
        let result = "";
        let match;
        while ((match = urlRegexp.exec(text)) !== null) {
            result += _escapeEntities(text.slice(curIndex, match.index));
            const url = match[0];
            const href = !/^https?:\/\//i.test(url) ? "http://" + encodeURI(url) : encodeURI(url);
            result += "<a " + attrs + ' href="' + href + '">' + _escapeEntities(url) + "</a>";
            curIndex = match.index + match[0].length;
        }
        return result + _escapeEntities(text.slice(curIndex));
    }

**Comment by sbouillon** [comment]
It should probably be modified to look like this…

```



const href = !/^https?:\/\//i.test(url) ? "https://" + encodeURI(url) : encodeURI(url);

function linkify(text, attrs) {
    attrs = attrs || {};
    if (attrs.target === undefined) {
        attrs.target = "_blank";
    }
    if (attrs.target === "_blank") {
        attrs.rel = "noreferrer noopener";
    }
    attrs = Object.keys(attrs || {}).map((key) => {
        const value = attrs[key];
        return `${key}="${escape(value)}"`;
    }).join(" ");
    let curIndex = 0;
    let result = "";
    let match;
    while ((match = urlRegexp.exec(text)) !== null) {
        result += _escapeEntities(text.slice(curIndex, match.index));
        const url = match[0];
        const href = !/^https?:\/\//i.test(url) ? "https://" + encodeURI(url) : encodeURI(url);
        result += `<a ${attrs} href="${href}">${_escapeEntities(url)}`;
        curIndex = match.index + match[0].length;
    }
    return result + _escapeEntities(text.slice(curIndex));
}
```

**Comment by sbouillon** [comment]
> I have the same issue. Since it is only happening when you open the website and click on editor, I suspect there is something wrong with the URL of the IFRAME. In the image you can clearly see, that the non secure page is requested by odoo. I tripplechecked my web base. That is correct, so I suspect in the below linkify is something fishy going on.
> 
> What do y'all think?
> 
> ```
>         const href = !/^https?:\/\//i.test(url) ? "http://" + encodeURI(url) : encodeURI(url);
> ```
> 
> function linkify(text, attrs) { attrs = attrs || {}; if (attrs.target === undefined) { attrs.target = "_blank"; } if (attrs.target === "_blank") { attrs.rel = "noreferrer noopener"; } attrs = Object.keys(attrs || {}).map((key)=>{ const value = attrs[key]; return `${key}="${escape(value)}"`; } ).join(" "); let curIndex = 0; let result = ""; let match; while ((match = urlRegexp.exec(text)) !== null) { result += _escapeEntities(text.slice(curIndex, match.index)); const url = match[0]; const href = !/^https?:///i.test(url) ? "http://" + encodeURI(url) : encodeURI(url); result += "<a " + attrs + ' href="' + href + '">' + _escapeEntities(url) + ""; curIndex = match.index + match[0].length; } return result + _escapeEntities(text.slice(curIndex)); }

Good find. 

It’s checking if the URL starts with “http://” or “https://**://**” before appending it to the link. If not, it adds “http://”. The resulting links are returned as a string.

**Comment by sbouillon** [comment]
This should fix the issue…



```
const href = !/^https?:\/\//i.test(url) ? "http://" + encodeURI(url) : encodeURI(url);

function linkify(text, attrs) {
    attrs = attrs || {};
    if (attrs.target === undefined) {
        attrs.target = "_blank";
    }
    if (attrs.target === "_blank") {
        attrs.rel = "noreferrer noopener";
    }
    attrs = Object.keys(attrs || {}).map((key) => {
        const value = attrs[key];
        return `${key}="${escape(value)}"`;
    }).join(" ");
    let curIndex = 0;
    let result = "";
    let match;
    while ((match = urlRegexp.exec(text)) !== null) {
        result += _escapeEntities(text.slice(curIndex, match.index));
        const url = match[0];
        const href = !/^https?:\/\//i.test(url) ? "http://" + encodeURI(url) : encodeURI(url);
        result += `<a ${attrs} href="${href}">${_escapeEntities(url)}`;
        curIndex = match.index + match[0].length;
    }
    return result + _escapeEntities(text.slice(curIndex));
}

```

**Comment by matthewlenz** [comment]
Note for others on GCP using the https load balancer direct to Odoo.  You can upgrade-insecure-requests to your CSP through the GCP LB using custom response headers and it works for Firefox but Chrome (Edge, etc) won't upgrade the request. :(

**Comment by matthewlenz** [comment]
@sbouillon that function is in addons/mail/static/src/js/utils.js if you want to submit a PR

**Comment by AquaMCU** [comment]
WOW. That was fun! Thank you for the help!

**Comment by AquaMCU** [comment]
How can I validate the fix? I tried to mount it into my docker container. I validated, that it is the new version, but I still have the issue.

**Comment by AquaMCU** [comment]
I tried the fix. Does not work :( I tried all configuration in my NGINX proxy that I have found and tripple checked the config in odoo. To recap:

1. Install ODOO
2. Install Website plugin and create website.
3. Open Website and go to exit --> BOOM

I use the official ODOO 17 docker image.  Can anyone tell me, where I can find the view that requests the website shown below the odoo menue? I want to see where the http:// request comes from.

**Comment by netfxtech** [comment]
I’m guessing you’re mapping the file via docker-compose and fixed the permissions, right?

The next step would probably replace odoo with ghcr.io/mendhak/http-https-echo:30 and see what nginx is passing through. 

I know I have it working correctly now. If you post the results of the headers I might be able to help you more.

**Comment by AquaMCU** [comment]
@netfxtech : Yes, I map the file via docker-compose 

The result of the echo container is:
{
  "path": "/",
  "headers": {
    "host": "XXXXXXX",
    "x-forwarded-scheme": "https",
    "x-forwarded-proto": "https",
    "x-forwarded-for": "XXXXXXX",
    "x-real-ip": "XXXXXXX",
    "user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "accept-language": "en-US,en;q=0.5",
    "accept-encoding": "gzip, deflate, br",
    "upgrade-insecure-requests": "1",
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "none",
    "sec-fetch-user": "?1",
    "pragma": "no-cache",
    "cache-control": "no-cache",
    "cookie": "frontend_lang=en_US; session_id=de084XXXXXXXb843fbcc48272ef7804; tz=America/Asuncion; cids=1"
  },
  "method": "GET",
  "body": "",
  "fresh": false,
  "hostname": "XXXXXXX",
  "ip": "XXXXXXX",
  "ips": [
    "XXXXXXX"
  ],
  "protocol": "https",
  "query": {},
  "subdomains": [],
  "xhr": false,
  "os": {
    "hostname": "3d9ccXXXXXXXf82d9a4"
  },
  "connection": {}
}

Thank you so much for the help!

**Comment by AquaMCU** [comment]
Just to clarify: This issue only happens when you edit your webpage. All other modules of ODOO run just perfect. 

I saw, that on my machine it uses the iframefallback. Since the fallback is not normal, I would like to search there.

**Comment by ARahmanK** [comment]
@shurshilov its from ngnix side. your ngnix not working properly.  One of my client face same issue.

**Comment by calwi** [comment]
I have this problem in Odoo 17, and none of the suggestions fixes the problem.

It's sat behind pfSense and HA Proxy.

Strangely, I have Odoo 16 and 15 instances running on the same setup, behind the same pfSense, using the same configurations and non of those have this problem.

I've been messing about with setting headers all day and so for now I think Odoo 17 will be parked up until something gives. 

Sadly and annoyingly.

**Comment by calwi** [comment]
> ```diff
> +        resp = request.redirect(path)
> +        resp.autocorrect_location_header = False
> +        return resp
> ```

This does nothing.

**Comment by dreispt** [comment]
I had this exact same problem is a recent Docker deployment.

As already mentioned in previous posts, some things to check are:

- The `web.base.url` is properly set to the https address
- The Website configuration, is also properly set with the site's address and using https
- The Odoo config optuon `proxy_mode=True` is set.
 
In my case, after doing so the problem persisted.
Upon investigation, it was a problem with the Nginx https configurations, that failed to redirect http requests to https.

My recommendation is to carefully review that configuration, based on the advice in the official documentation:
https://www.odoo.com/documentation/17.0/administration/install/deploy.html#https

**Comment by calwi** [comment]
> I had this exact same problem is a recent Docker deployment.
> 
> As already mentioned in previous posts, some things to check are:
> 
> * The `web.base.url` is properly set to the https address
> * The Website configuration, is also properly set with the site's address and using https
> * The Odoo config optuon `proxy_mode=True` is set.
> 
> In my case, after doing so the problem persisted. Upon investigation, it was a problem with the Nginx https configurations, that failed to redirect http requests to https.
> 
> My recommendation is to carefully review that configuration, based on the advice in the official documentation: https://www.odoo.com/documentation/17.0/administration/install/deploy.html#https

... and if you're NOT using Nginx? HA Proxy has the same issue... Works fine in versions <17

**Comment by PieterPaulussen** [comment]
This solution worked for my configuration as well. Thanks for the comment!

> > I have been trying to debug this for hours, and finally found a solution for Traefik. What finally worked:
> > 
> > * Set web.base.url to https://mydomain.com
> > * Configured proxy headers (in Traefik in my case):
> >   ```
> >   - traefik.http.middlewares.upgrade-insecure-requests.headers.customrequestheaders.X-Forwarded-Proto=https,wss
> >   - traefik.http.middlewares.upgrade-insecure-requests.headers.customresponseheaders.Content-Security-Policy=upgrade-insecure-requests
> >   ```
> > 
> > Without this, the browser still tries to respond using HTTP, rather than HTTPS. I see this in Chrome's debug console:
> > `Mixed Content: The page at 'https://shop.mysite.com/web#action=289&cids=1&menu_id=175' was loaded over HTTPS, but requested an insecure frame 'http://shop.mysite.com/'. This request has been blocked; the content must be served over HTTPS.`
> > I honestly also don't understand the explanation from @rdeodoo though - to me this looks like an issue with the frontend, not the backend, so I don't see why X-Forwarded-Proto should make a difference. And setting the custom response header as shown above seems like a workaround, but not like a solution that addresses the root cause.
> > But in any case, it works for me now.
> > Note that there is one more place that I noticed fails even with the above workaround: The stripe integration is unable to automatically register the webhook, because it tries to register an HTTP endpoint in Stripe. So I had to follow the docs to enable it manually.
> 
> Are you using a cloudflare tunnel and then sending it to Traefik? If so, are you using a config file on the server or configuring it through Cloudflare’s website?
> 
> I can post my settings either way because I have it working. I’m not knowledgeable enough regarding the issue to argue why this or that doesn’t work, but I know what settings work for me.

**Comment by PieterPaulussen** [comment]
> I have been trying to debug this for hours, and finally found a solution for Traefik. What finally worked:
> 
> * Set web.base.url to https://mydomain.com
> * Configured proxy headers (in Traefik in my case):
>   ```
>   - traefik.http.middlewares.upgrade-insecure-requests.headers.customrequestheaders.X-Forwarded-Proto=https,wss
>   - traefik.http.middlewares.upgrade-insecure-requests.headers.customresponseheaders.Content-Security-Policy=upgrade-insecure-requests
>   ```
> 
> Without this, the browser still tries to respond using HTTP, rather than HTTPS. I see this in Chrome's debug console:
> 
> `Mixed Content: The page at 'https://shop.mysite.com/web#action=289&cids=1&menu_id=175' was loaded over HTTPS, but requested an insecure frame 'http://shop.mysite.com/'. This request has been blocked; the content must be served over HTTPS.`
> 
> I honestly also don't understand the explanation from @rdeodoo though - to me this looks like an issue with the frontend, not the backend, so I don't see why X-Forwarded-Proto should make a difference. And setting the custom response header as shown above seems like a workaround, but not like a solution that addresses the root cause.
> 
> But in any case, it works for me now.
> 
> Note that there is one more place that I noticed fails even with the above workaround: The stripe integration is unable to automatically register the webhook, because it tries to register an HTTP endpoint in Stripe. So I had to follow the docs to enable it manually.

This solution worked for my configuration with Traefik as well. Thanks for the comment!

**Comment by ioscanner** [comment]
For everyone having this issue still with version 17.  Be sure you are using the nginx config example from the documentation.

#odoo server
upstream odoo {
  server 127.0.0.1:8069;
}
upstream odoochat {
  server 127.0.0.1:8072;
}
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

# http -> https
server {
  listen 80;
  server_name odoo.mycompany.com;
  rewrite ^(.*) https://$host$1 permanent;
}

server {
  listen 443 ssl;
  server_name odoo.mycompany.com;
  proxy_read_timeout 720s;
  proxy_connect_timeout 720s;
  proxy_send_timeout 720s;

  # SSL parameters
  ssl_certificate /etc/ssl/nginx/server.crt;
  ssl_certificate_key /etc/ssl/nginx/server.key;
  ssl_session_timeout 30m;
  ssl_protocols TLSv1.2;
  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers off;

  # log
  access_log /var/log/nginx/odoo.access.log;
  error_log /var/log/nginx/odoo.error.log;

  # Redirect websocket requests to odoo gevent port
  location /websocket {
    proxy_pass http://odoochat;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # Redirect requests to odoo backend server
  location / {
    # Add Headers for odoo proxy mode
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect off;
    proxy_pass http://odoo;

    # Enable HSTS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
    # requires nginx 1.19.8
    proxy_cookie_flags session_id samesite=lax secure;
  }

  # common gzip
  gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript;
  gzip on;
}

**Comment by matthewlenz** [comment]
This issue has nothing to do with any reverse proxy being used.   It's a bug in magento 17.

**Comment by bangdh** [comment]
I fix nginx.conf as following intructions, It worked!
https://www.odoo.com/documentation/16.0/administration/install/deploy.html#id7

**Comment by psy0rz** [comment]
in our case the server redirects to a http url somehow:
![image](https://github.com/odoo/odoo/assets/1179017/e0f36500-f2ce-4d42-a2cd-bf803538ab85)

(note that this is apache and i will try to translate the previously mentioned deploy documentation)

**Comment by psy0rz** [comment]
ok it was just a invalid expression in this line:
```
RequestHeader set X-Forwarded-Proto https
```
(it used some kind of variable which was invalid i think)

**Comment by Ujeeee** [comment]
> When I encountered this problem, I set "`web.base.url`" to "`https://mydomain.com`", "`web.base.url.freeze`" to "`True`", and finally added "`proxy_redirect http://$scheme://;`" in the site settings of nginx, and then I could edit the website page normally.

I added that nginx setting to cloudflare, then it work for me

**Comment by wild-bil** [comment]
For those on apache with bitnami stack I got the following to work

`<IfModule headers_module>
    #
    # Avoid passing HTTP_PROXY environment to CGI's on this or any proxied
    # backend servers which have lingering "httpoxy" defects.
    # 'Proxy' request header is undefined by the IETF, not listed by IANA
    #
    Header always set Content-Security-Policy "upgrade-insecure-requests;"
    RequestHeader unset Proxy early
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
    RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}

</IfModule>`

**Comment by bobslee** [comment]
FYI - Concerning issues with the combination of **Cloudflare and Nginx**
The following actions could solve it (at least on my side):

Cloudflare:
- SSL/TLS: Full
- Disable Cloudflare Brotli (compression)
- Purge the Cloudflare Cache

Odoo:
- Ensure Odoo is in proxy_mode

Nginx config, basics according to:
https://www.odoo.com/documentation/17.0/administration/on_premise/deploy.html?highlight=nginx#https

**Comment by sumit-poditservices** [comment]
> Is there a solution for apache?



> I got the following to work for those on Apache, likely with bitnami stack. @eperezsolla @psy0rz
> 
> Add this to /opt/bitnami/apache/conf/httpd.conf
> 
> I would love someone to chime in and tell me why this worked!!! 😃
> 
> I don't have a `web.base.url.freeze` I tried but then deleted it. I did set `web.base.url` to ` https://mydomain.com`
> 
> ```
> 
> <IfModule headers_module>
>     #
>     # Avoid passing HTTP_PROXY environment to CGI's on this or any proxied
>     # backend servers which have lingering "httpoxy" defects.
>     # 'Proxy' request header is undefined by the IETF, not listed by IANA
>     #
>     Header always set Content-Security-Policy "upgrade-insecure-requests;"
>     RequestHeader unset Proxy early
>     RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
>     RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}
> 
> </IfModule>
> ```

Line --- 
Header always set Content-Security-Policy "upgrade-insecure-requests;"

Make all request upgraded to https . So as soon a request as http comes it also turn up into https.

**Comment by hibahodges** [comment]
> set dynamic | X-Forwarded-Host | http.host

This is an older post, but we just upgraded from V15 to V17 using odoo.sh and have hit the same problem.   I tried doing the request header change above in cloudflare but no luck...obviously the changed something in v17 thats mucked it up and it just hasn't been fixed yet (or v15 would never have worked either).

Anyone else have any other idea's?  These are also set in cloudflare...
Always Use HTTPS
Redirect all requests with scheme “http” to “https”. This applies to all http requests to the zone.

Automatic HTTPS Rewrites
Automatic HTTPS Rewrites helps fix mixed content by changing “http” to “https” for all resources or links on your web site that can be served with HTTPS.

**Comment by rdeodoo** [comment]
> .obviously the changed something in v17 thats mucked it up and it just hasn't been fixed yet **(or v15 would never have worked either).**

There is nothing to be fixed, as explained.

The website preview in the iframe was introduced in Odoo 16 only, so the wrong configuration of your side would not be detected in Odoo 15 and you would not see any issue (while it was still wrong).
But in Odoo 16 and later, this configuration issue is problematic to access the website app, since it's loaded in the iframe.

The full explanation was given here: https://github.com/odoo/odoo/issues/104597#issuecomment-1496279435
And also some information here: https://github.com/odoo/odoo/issues/104597#issuecomment-1505563744

All the messages on this thread are actually confirming what I explained, it's always a misconfiguration regarding the `X-Forwarded-Proto` at the end.

We can't provide a detailed assistance about all the provider being used, but the explanation I mentioned should give you a good understanding on the issue and why it happen and where to look to fix it.

Of course, we may have missed something somewhere on our side, but it's very unlikely, as we have done quite some investigation as you can see, and we have a lot of setup working correctly. Plus, people reporting the issue here ultimately made it work by fixing **their** configuration.

**Comment by matthew-lenz-otr** [comment]
@rdeodoo, it's not a mis-configuration exactly.  The issue is that Odoo is making incorrect assumptions about the incoming request/environment that are negatively impacting the response.  Odoo should be able to function properly without a requiring a reverse proxy to "fix up" the response.  I've worked with hundreds of applications behind SSL terminating reverse proxies and never run into issues like these that weren't the fault of the application itself.  IMO, the x-forwarded-proto header (which is a de-facto standard) should be good enough for Odoo to property write urls.

**Comment by rdeodoo** [comment]
> The issue is that Odoo is making incorrect assumptions about the incoming request/environment that are negatively impacting the response.

I don't think so, we trust exactly what we want to trust and should trust, and we do no assumptions at all as explained https://github.com/odoo/odoo/issues/104597#issuecomment-1496279435 and https://github.com/odoo/odoo/issues/104597#issuecomment-1505563744

> Odoo should be able to function properly without a requiring a reverse proxy to "fix up" the response.

There is no fix up needed whatsoever, just setting X-Forwarded-<xyz> correctly along the chain. I am not sure to understand your point, which fix up are you referring to?

> I've worked with hundreds of applications behind SSL terminating reverse proxies and never run into issues like these that weren't the fault of the application itself.

From what I understand, you mean that without the X-Forwarded-Proto & co being correctly set, the apps were able to work correctly? It means that either the app was always forcing https regardless of the initial client call, or doing magic?

>  IMO, the x-forwarded-proto header (which is a de-facto standard) should be good enough for Odoo to property write urls.

Isn't it the case and what we explained?

Maybe I am misunderstanding something, but I went to the edge of my knowledge on this one in my initial summary and next replies, the only thing I can do is summon @Julien00859 for a triple check about your previous messages or for a more neutral point of view. But I think his summary is also very clear and no one actually came with a concrete exemple or configuration about why would something be wrong in Odoo.

**Comment by cokotracy** [comment]
If you’re self-hosting Odoo ERP behind Nginx with SSL (https) and you’re struggling with broken stylesheets, missing JavaScript, can not edit website or a website editor that refuses to load properly, this guide is for you. I personally recently went through this painful journey while deploying Odoo 18 Community Edition on a my own Contabo VPS. The symptoms were frustrating me until this night, but the root cause was ultimately misconfiguration in the reverse proxy and asset routing of my Odoo ERP.

I checked up and down, day by day and finally discover that everything was working okey if editing the website on IP address , I mean without using a proxy server.

**### SOLUTION (Step-by-Step)**

**Step 1: Enable proxy_mode in Odoo Config**

Open your Odoo config file:

sudo nano /etc/odoo/odoo.conf

Make sure the following is present:

proxy_mode = True

This tells Odoo to trust the proxy headers passed from Nginx.

**Step 2: Update Nginx Configuration**

Open your Nginx site configuration:

sudo nano /etc/nginx/sites-available/odoo

Ensure the config includes these key directives:

server {

    listen 80;

    server_name yourdomain.com;

    return 301 https://$host$request_uri;

}

server {

    listen 443 ssl;

    server_name yourdomain.com;
    ssl_certificate     /etc/letsencrypt/live/yourdomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yourdomain.com/privkey.pem;
    add_header Content-Security-Policy "upgrade-insecure-requests;";
   
 location / {
        proxy_pass http://127.0.0.1:8069;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /web/assets/ {
        proxy_pass http://127.0.0.1:8069;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        expires 864000;
    }

    location /web/static/ {
        proxy_pass http://127.0.0.1:8069;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        expires 864000;
    }

}

Then test and reload Nginx:

sudo nginx -t && sudo systemctl reload nginx

**Step 3: Restart Odoo**

After making config changes, restart Odoo:

sudo systemctl restart odoo

**Optional**: Clear asset cache to force regeneration:

sudo rm -rf /var/lib/odoo/.local/share/Odoo/web/assets/*

**Step 4: Set web.base.url (Optional)**

Inside Odoo:

    Go to: **Settings > Technical > Parameters > System Parameters**
    Add:
        web.base.url: https://yourdomain.com
        web.base.url.freeze: True

This prevents Odoo from defaulting back to http://localhost:8069 in asset links.

**### Why This Happens (Odoo 16+)**

In Odoo 15 and earlier, the website editor opened in a new browser tab. But starting with Odoo 16, the editor is embedded in an iframe. This means any HTTP vs HTTPS mismatch between the parent and iframe causes content to be blocked for security reasons.

Also, Odoo dynamically serves web assets using hashed paths like:

/web/assets/3/somehash/web.assets_web.min.js

If Nginx isn’t set to route /web/assets/ and /web/static/ correctly to Odoo, you’ll see endless 404s.
Bonus: Mixed Content Warning Fix

Mixed content warnings are triggered when some resources load over HTTP in an HTTPS page. To force all URLs to upgrade:

add_header Content-Security-Policy “upgrade-insecure-requests;”;

This single line fixes a lot of iframe and asset issues in the Odoo backend.

**Conclusion**

Odoo’s flexibility is powerful, but its reverse proxy requirements can cause frustrating issues when misconfigured. Once we got the headers, proxy mode, and asset routing right, the site editor loaded instantly, assets were served over HTTPS, and all the 404s vanished.

If you’re running into this same wall, follow the steps above exactly. It took us hours of troubleshooting, reading through GitHub threads, and testing config changes to get this stable. Hopefully this guide saves you that pain.

If you’d like help deploying or debugging your Odoo instance,[ reach out to our team](https://propellex.co/) or leave a comment below.

**Happy deploying Odoo 18 with https !**

you can learn more also from PROPELLEX.COM : 
https://propellex.co/fixing-odoo-web-assets-and-website-editor-behind-nginx-https-reverse-proxy/
