### ISSUE TITLE
Point of sale user access right problem

### ISSUE THREAD

**Issue by ahmedhegazyfv** [odoo/odoo#11177]
Impacted versions:9

Steps to reproduce:2

Current behavior:Point of sale user try to start new session the get this error:
 "The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: account.bank.statement, Operation: read)"

Expected behavior:start new session normally

Video/Screenshot link (optional):

**Comment by flotho** [comment]
Hi, is your user Responsible of point of sale?

**Comment by ahmedhegazyfv** [comment]
No, But when I make the user as responsible it solved , but I think this is not the default case which mean the user can start the session even he is not responsible for the session ?

**Comment by invitu** [comment]
same problem here in v9 (7ca31fdcde9616b6b5876fa6f79fcc3835ccdccb)
my user is Responsible of pos

**Comment by jorenvo** [comment]
In Odoo versions < saas-8 (specifically from 8cedda60cca8a63f3ad5163aa3abef246b0b4b79), POS users are not supposed to be able to open or close sessions. So in those versions you need a POS manager to open a POS session with the correct POS user set as the responsible.

From saas-8 and up, we have gotten rid of that functionality. In those versions a POS user should be able to open and close POS sessions on his own by default.

Of course these are just defaults and you can customize Odoo to do anything you want by modifying or deleting the relevant Access Control Lists and/or Record Rules (in Debug mode, Settings > Technical > Security).

**Comment by invitu** [comment]
Hello

I read your advice but I think there is still a problem : 

Steps to Reproduce : 
- go to runbot v9 (actually is 98552752035db059af7315e4fcb1cb4bcf75e8f6)
- login with admin
- check the rights in security : pos responsible has the right to read/write/create/delete a bank.statement
![screenshot1](https://cloud.githubusercontent.com/assets/7600872/13754329/a9fcaece-e9ba-11e5-8573-4b87a18dae29.png)

- assign rights to user demo (only pos reponsible... important remove any accounting rights)
![screenshot2](https://cloud.githubusercontent.com/assets/7600872/13754336/b53c23fa-e9ba-11e5-822d-683698598596.png)

- create a new pos Demo
![screenshot3](https://cloud.githubusercontent.com/assets/7600872/13754365/c43f69ca-e9ba-11e5-83f9-1a6d6a1b6404.png)

- login with demo
- create a new session on the Demo pos
![screenshot4](https://cloud.githubusercontent.com/assets/7600872/13754377/d3dc60d6-e9ba-11e5-99fd-86e39364e3bd.png)
![screenshot5](https://cloud.githubusercontent.com/assets/7600872/13754381/dadf7878-e9ba-11e5-8c3c-f18670395a1b.png)


Odoo Warning - Access Error
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

(Document type: account.bank.statement, Operation: read)

Could you check again ?

best regards

**Comment by invitu** [comment]
If you set accounting rights to accountant (who has the right to read/write/create/delete a account.bank .statement), the error is gone.
There might be some wrong check rights methods

**Comment by elicoidal** [comment]
I have identified the same issue here. I cannot create a simple POS 
user. It needs to be "Accountant" at least for bank statement write and 
read access (which he is supposed to have by default in standard ACL)

**Comment by jorenvo** [comment]
As I mentioned before in Odoo access to records is managed by both the relevant ACLs *and* record rules. Record rules apply after application of the ACL. A record rule specifies a condition that must be satisfied before a CRUD operation is allowed [1]. In this case there is a record rule called `Point Of Sale Bank Statement Line POS` which is prohibiting a POS user from executing any operation on account.bank.statement.line records unless that record is linked to a account.bank.statement with a pos_session_id, which won't be the case when you open a new session. There is also another one called `Point Of Sale Bank Statement POS User`. Disabling both of those should resolve the problems everyone is having.

[1] https://www.odoo.com/documentation/8.0/reference/security.html

**Comment by invitu** [comment]
Dear @jorenvo 
Thanks for clarifying.
In my case, disabling Record Rule `Point Of Sale Bank Statement POS User` did it

Thank you

**Comment by elicoidal** [comment]
@jorenvo I understand your point but do not agree with the solution.
1. These rules should be working in theory as is
2. in vanilla Odoo, we cannot create a POS User without an error
Your fix works but that is not the point as both above points are not fixed

**Comment by elicoidal** [comment]
@jorenvo What I do not understand then is why the button "Open"/"Close" POS is visible to POS Users if they are not supposed to use it.
It is extremely uncomfortable to explain to the users that they can click on a button which is useless and trigger an error.

**Comment by invitu** [comment]
Another access right issue... Managing cashbox is not possible in pos v9 with default settings.
We have to add access rights to account.bank.statement.cashbox and account.bank.statement.cashbox.line to pos responsible
Should we open a new issue for that one ?

**Comment by nmthembu** [comment]
Please help: I get the following error when I try to open a Pos session with a newly created user with user access under point of sales access rights
Odoo Warning - Access Error
The requested operation cannot be completed due to security restrictions. Please contact your system administrator.
(Document type: account.bank.statement, Operation: read)

**Comment by houssine78** [comment]
Hi @jorenvo 

For what I've been experienced the record rule also apply to the pos manager which is a bug AFAIU...

**Comment by odoosin** [comment]
Here I see we have to give access to accounting module to Pos users in order to open session. I think Pos and Accounting user accessibility should be separated from each other.

A Pos user can see records created by all other users. It looks like POS wasn't designed by considering multiple shops.
