### ISSUE TITLE
Error: Widget type 'html' is not implemented

### ISSUE THREAD

**Issue by odoo-mohsin** [odoo/odoo#11627]
Impacted versions: 9.0 e

Steps to reproduce: Click on any menu under administrator settings, it pops up the error.

Current behavior:
http://localhost:8069/web/content/9945-5e80088/web.assets_backend.js:3662
Traceback:
FormRenderingEngine<.render_to/<@http://localhost:8069/web/content/9945-5e80088/web.assets_backend.js:3662:1
_.forEach@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:12:558
FormRenderingEngine<.render_to@http://localhost:8069/web/content/9945-5e80088/web.assets_backend.js:3661:1735
FormView<.load_form@http://localhost:8069/web/content/9945-5e80088/web.assets_backend.js:3602:278
FormView<.view_loading@http://localhost:8069/web/content/9945-5e80088/web.assets_backend.js:3599:2451
View<.load_view/<@http://localhost:8069/web/content/9945-5e80088/web.assets_backend.js:3033:160
.Deferred/promise.then/</</<@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:650:678
jQuery.Callbacks/fire@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:649:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:651:31
ParentedMixin.alive/</<@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:2607:404
.Deferred/promise.then/</</<@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:650:678
jQuery.Callbacks/fire@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:649:198
.Deferred/promise.then/</</<@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:650:849
jQuery.Callbacks/fire@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:649:198
.Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:651:31
jQuery.Callbacks/fire@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:649:198
.Deferred/promise.then/</</<@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:650:849
jQuery.Callbacks/fire@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:649:198
.Deferred/promise.then/</</<@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:650:849
jQuery.Callbacks/fire@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:644:281
jQuery.Callbacks/self.fireWith@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:649:198
done@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:1040:86
.send/callback@http://localhost:8069/web/content/9944-cc2615b/web.assets_common.js:1060:15

Expected behavior:
Records should be opened properly.

Video/Screenshot link (optional):
http://www.screencast.com/t/iUYRGWro

**Comment by mywave82** [comment]
I got similar problem, after I told odoo to update the local module list, I can no longer click on modules/apps.

[http://picpaste.com/odoo9-deleteme-CudCCcRt.png]

**Comment by Yenthe666** [comment]
Hi @odoosin and @mywave82,

I can no longer reproduce this issue on the latest Odoo code.
If you still face this issue please update your Odoo codebase and it should be working.

Regards,
Yenthe

**Comment by ramganesh19** [comment]
I am also getting similar with after download the 9.0 branch copy and when running the application
additionally i dont see any apps

Apps
Settings
 Administrator 
×
Change My Preferences
×
Odoo Client Error
Uncaught Error: Widget type 'html' is not implemented
http://localhost:8069/web/content/345-0689709/web.assets_backend.js:3592
Traceback:
Error: Widget type 'html' is not implemented
    at http://localhost:8069/web/content/345-0689709/web.assets_backend.js:3592:104
    at Function._.each._.forEach (http://localhost:8069/web/content/342-edb5d4e/web.assets_common.js:12:558)
    at OdooClass.render_to (http://localhost:8069/web/content/345-0689709/web.assets_backend.js:3591:1704)
    at OdooClass.load_form (http://localhost:8069/web/content/345-0689709/web.assets_backend.js:3527:394)
    at OdooClass.view_loading (http://localhost:8069/web/content/345-0689709/web.assets_backend.js:3524:2341)
    at Object.<anonymous> (http://localhost:8069/web/content/345-0689709/web.assets_backend.js:2980:314)
    at Object.<anonymous> (http://localhost:8069/web/content/342-edb5d4e/web.assets_common.js:650:681)
    at fire (http://localhost:8069/web/content/342-edb5d4e/web.assets_common.js:644:299)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/content/342-edb5d4e/web.assets_common.js:649:198)
    at Object.deferred.(anonymous function) [as resolve] (http://localhost:8069/web/content/342-edb5d4e/web.assets_common.js:651:56)
![image](https://cloud.githubusercontent.com/assets/12521269/17433528/cfc29732-5aca-11e6-8e6a-33761c5e39af.png)

**Comment by Yenthe666** [comment]
@ramganesh19 can you reproduce this on an official Odoo instance? (runbot.odoo.com)

**Comment by seyed-mohammad-motahar** [comment]
I got the same error in V10 enterprise. 

What I did to fix the issue : 

1. re-Installed  all dependencies again
2. Removed custom_addons from the path (So only load odoo standard modules)
3. Updated the odoo to the latest V10 and also updated odoo enterprise folder to latest
4. reinstall nodeJS using different methods. 
5. Removed all development databases and started fresh by creating a blank new db

When the blank db is created I tried to open apps menu and below is the error.

![image](https://cloud.githubusercontent.com/assets/4558819/21097776/311f5ea2-c0a1-11e6-92bd-0eb221a87bc4.png)

**Comment by seyed-mohammad-motahar** [comment]
The only workaround I found so far is to activate developer mode (assets)

**Comment by Armitxes** [comment]
Got the newest Odoo 10 sources (with enterprise), fresh db, and the absolute same issue. Same happens on older dbs.

`Uncaught Error: Widget type 'html' is not implemented`

**Comment by NeoPolus** [comment]
I also face this problems when using the official docker container (https://hub.docker.com/_/odoo/).

**Comment by Armitxes** [comment]
okay, fixed here. One import in a module was wrong.

`openerp.addons.web.http import Controller, route, request`

made it to search http class in "/openerp/addons/web/". Changing it to

`from openerp.http import request, route, Controller`

helped so it searches the class in "/odoo/addons/web/"

**Comment by thinkwelltwd** [comment]
[quote]
okay, fixed here. One import in a module was wrong.

openerp.addons.web.http import Controller, route, request

made it to search http class in "/openerp/addons/web/". Changing it to

from openerp.http import request, route, Controller

helped so it searches the class in "/odoo/addons/web/"
[/quote]

I have the same problem, and can only fix it by activating the developer mode. But you don't mention _which_ module you made the change to. Could you give more details about where you corrected the import?

**Comment by Armitxes** [comment]
It was a custom module which is exactly why you can't point your finger on a specific module. The big use issue is that some modules (such as web)  exist more than once and share same namespaces & classes. This easily leads for python to point the wrong class.

If you are using some sort of debugger (I. e. the one from pycharm or vs-products you can easily determine the script which inherits that HTTP wrongly by looking at the logs / local variables.  If you then open that file and do a shift-leftclick on the inherit, you can see by path which http is being inherited by python and replace it with the correct path.

Hope I could help a bit.

**Comment by diezcode** [comment]
I've updatet the odoo10 version to the github stand 24.03 and the error is gone.

**Comment by gregimagines** [comment]
I just started having this issue. We ended up reinstalling Odoo and our database and can't get rid of it. I've tried disabling custom addons and has not helped. Using Enterprise 10 nightly build for August 1. Tried using another nightly build and did not help.

**Comment by farzeni** [comment]
Same here. We made a fresh installation on a new database with Enterprise modules but without other custom modules and the problem is still there. 
We are using odoo 10.0.

**Comment by ndemoreau** [comment]
Same here...

**Comment by ndemoreau** [comment]
I get this error in my browser console when opening "Apps" in Odoo backend:

warning: Some modules could not be started 
Missing dependencies:    ["web_editor.summernote"] 
Non loaded modules:      (15) ["web_editor.editor", "web_editor.rte", "web_editor.rte.summernote", "web_editor.widget", "web_editor.snippet.editor", "web_editor.snippets.options", "web_editor.tour", "web_editor.transcoder", "web_editor.translate", "website.editor", "website.translator", "website.contentMenu", "website.snippets.editor", "website.rte.summernote", "website.snippets.editor.gallery"] 
Debug:                   {web_editor.editor: {…}, web_editor.rte: {…}, web_editor.rte.summernote: {…}, web_editor.widget: {…}, web_editor.snippet.editor: {…}, …}

The error disappears when going to developer mode with assets.

This is what causes the problem. But I don't have the solution...

**Comment by mstuttgart** [comment]
Its seen a problem on  update *web* module and browser cache. I fix it updating *web* module

```
odoo.py -u web -d databasename --stop-after-init
```
restarting Odoo server and opening a *new private window* of my browser.

**Comment by ndemoreau** [comment]
@mstuttgart you are totally right. It solved the problem for me as well. 

Any idea why this occurs? 

I didn't update the web module when this started to happen.

**Comment by Yenthe666** [comment]
@ged-odoo do you have any idea?

**Comment by ged-odoo** [comment]
@Yenthe666 not sure. I think that this thread talks about a few different issues.  It looks like we have at least a problem with the assets: the bundle is not properly generated (because going to debug=assets solves the issue), then we have a problem with a missing js module (web_editor.summernote), and a missing js file (the one with html widget)

For the html widget, for historical/bad reasons, it is not located in addons/web, but in addons/web_editor, so it may be that the addon web_editor is not properly installed or something.  From what I see, I do not have a clear picture of what exactly is happening.  I can just tell you that I would like to at least have a basic FieldHTML in web, even if it does not have a full blown editor.

**Comment by Yenthe666** [comment]
Alright, thank you for the feedback. Is there anything planned to better handle the assets bundle or the FieldHTML in web? Or what is the plan for this?

**Comment by ged-odoo** [comment]
@Yenthe666 well, i can only give you a generic answer for the asset bundles. Any bug that we can identify clearly should be fixed asap.  Such bugs make the web client basically unusable, so yes, we can fix them.  However, I personally think that our implementation is too naive, and we won't solve the generic problem of managing assets without rethinking the whole system.  It may happen, but I need to first have a prototype, to be able to articulate the problems I want to solve, and to sell it properly. So, it is not clear for now.

For the FieldHTML, I think that a few lines of JS would solve cleanly the issue, and this can be done basically at any time.  Just need to extend FieldText, override its renderReadonly method to display html instead of text, and then add it to the field registry.

**Comment by valentinvegaa** [comment]
I have the exactly same problem... is there any development in the solution of this?

**Comment by valentinvegaa** [comment]
Ok, in my case i found a solution...
I tried installing/uninstalling several different modules trying to generate again the file web.assets_backend.js because that was the file that must have the javascript corresponding to the classes 'summernote' of the module web_editor... if i see the debugger/network i noticed that that file was called and returned 200 ok but 0 bytes... that drove me crazy for several days, until i found the problem... that file (and several others) where stored in the database (i think) so these file where never regenerated because they where saved as attachments in odoo.
So the solution was... go to:
configuration-->technical-->attachments
then select the desired stored javascript (in my case web_editor.summernote.js) and i delete it... then it should be generated again and in the proper way.

greetings

**Comment by valentinvegaa** [comment]
Ok, in my case i found a solution...
I tried installing/uninstalling several different modules trying to generate again the file web.assets_backend.js because that was the file that must have the javascript corresponding to the classes 'summernote' of the module web_editor... if i see the debugger/network i noticed that that file was called and returned 200 ok but 0 bytes... that drove me crazy for several days, until i found the problem... that file (and several others) where stored in the database (i think) so these file where never regenerated because they where saved as attachments in odoo.
So the solution was... go to:
configuration-->technical-->attachments
then select the desired stored javascript (in my case web_editor.summernote.js) and i delete it... then it should be generated again and in the proper way.

greetings

**Comment by Maurice67205** [comment]
We have the same problem when restoring a database from customer

**Comment by gogomarine** [comment]
Same here. V10

**Comment by sylnsr** [comment]
Same issue here, but simple to fix with running this against the affected DB:
    DELETE FROM ir_attachment WHERE datas_fname SIMILAR TO '%.(js|css)'

**Comment by Yenthe666** [comment]
Hi all,

As the V9 is no longer official supported and we can't reproduce this on V10 I'm closing this issue.
Don't hesitate to post back with more steps about how to reproduce it on a supported version.

Regards,
Yenthe

**Comment by unnati-badgujar** [comment]
Hii All,

I'm Using odoo12
At the time of sending automation mail this error is occur. Can anyone help me,

![e1](https://user-images.githubusercontent.com/59116378/94339269-41e8fa00-0016-11eb-9ca2-5e9a708aebab.png)
![err](https://user-images.githubusercontent.com/59116378/94339270-457c8100-0016-11eb-8414-45ba6e473245.png)
