### ISSUE TITLE
Version 9 Purchase modul has wrong rounding

### ISSUE THREAD

**Issue by Derter** [odoo/odoo#14054]
Impacted versions: 9 

Steps to reproduce: taxes 19% not in price included, make a vendor bill, put one product with for exp. 707,02 and one with 66,39 

Current behavior: 707,02+66,39*1,19=920,3579 price to pay: 920,35

Expected behavior: 920,3579 should be price to pay 920,36

Video/Screenshot link (optional): 
![bildschirmfoto 2016-10-28 um 16 23 03](https://cloud.githubusercontent.com/assets/14194754/19809730/d5cac0ee-9d2a-11e6-920e-98bb49ed8b0b.png)

**Comment by dansanti** [comment]
Hi! First try configuring global rounding taxes, by default is per line  taxes rounding

**Comment by Derter** [comment]
@dansanti 
Thanks for answer. Were do I find this configuration?

Its not on taxes, journal entries, mutli currencies or decimal spaces.

**Comment by Derter** [comment]
@dansanti 
found it in the company configuration

**Comment by Derter** [comment]
Hello Odoo,

I've made the changes @dansanti told me to: configuration->company->round globally

But we faced another rounding issue when setting it to globally. Now a sales order has other sum than the invoice. Even though they have the same currency and the same tax. Don't they round on based on the same factors? How is this possible? 

Looking forward to hear an answer here. Thank you.

![bildschirmfoto 2016-11-07 um 11 49 49](https://cloud.githubusercontent.com/assets/14194754/20055216/5cf6a116-a4e0-11e6-9f5e-21982295be42.png)
![bildschirmfoto 2016-11-07 um 11 49 57](https://cloud.githubusercontent.com/assets/14194754/20055223/61274902-a4e0-11e6-80c8-60be06a9d058.png)

**Comment by Derter** [comment]
still waiting for an solution here. Thank you.

**Comment by Yenthe666** [comment]
@qdp-odoo can I ask you for input here?

**Comment by Derter** [comment]
Still waiting for answer here, thanks.

**Comment by qdp-odoo** [comment]
I would have confirmed the bug, if I would have had reproduced the bug...

but I tested your use case, on the latest v9, and the SO is computed like the invoice. Maybe it has already been fixed in a recent patch?

Can you try to reproduce on runbot?

**Comment by qdp-odoo** [comment]
Sorry, actually I can reproduce it -_-. 

let me reopen that

**Comment by qdp-odoo** [comment]
Well... actually, after a bit of researches, it appears that we already refused to consider this behavior as a bug. 

The problem is related to the 'round globally' method, and we already had a lot of discussions to remove completely that option. So far we kept it, because people wanted it but nowadays maybe it would be different if we'd ask again.

If you use tax included, you cannot use round globally or this problem will arise. Switch the round per line

**Comment by Yenthe666** [comment]
Oh, I'm sorry I didn't know that @qdp-odoo. Is this documented somewhere however?

**Comment by wtaferner** [comment]
@qdp-odoo @Yenthe666 
Well, I am sorry that I think that you try to push it away, but it could eventually be resolved (I don't say it is a bug as it is just not mature enough yet)
https://github.com/odoo/odoo/pull/8427 has a clear path to it although it needs acceptance of the issue first...and round globally is crucial for net calculation of taxes. So a combination and more configuration levels are needed to handle this right...but yeah, let's hope that at some point there will be the will to handle this issue and not to reject it or even remove round globally completely.

**Comment by gdgellatly** [comment]
Round globally is a legal requirement in Australia for ex tax, and best
practice in NZ. It does not need a lot of configuration changes for the
simple case.  If round globally and incl tax then round per line.

We find that for supplier systems matching we need to set per supplier this
setting.

**Comment by qupro** [comment]
Regardeless of "Round globally" use, this is still an issue since using round per line result in bad calculation, no?.

Here is another example with round per line, 5 decimals and 21% TAX (journal with TAX not included in price) , and Odoo v9 
![calculation error](https://cloud.githubusercontent.com/assets/5942916/20649155/9a005d94-b4b8-11e6-9dad-11b4b68bb123.png)

**Comment by wtaferner** [comment]
@gdgellatly 
Right, it is just the way how it is computed and the law is normally not giving you the right to decide yourself most of the times. Anyway, for the most use cases, and if you do not mix or are not forced to mix, it works (there are some corner cases which should be tackled and I hope that these will be respected at some point)

@qupro 
What is wrong in your example? At least I do not get the error in  your use case.

**Comment by qupro** [comment]
Sorry, wrong image, this is the good one:
![calculation error2](https://cloud.githubusercontent.com/assets/5942916/20649816/dc653268-b4c7-11e6-9214-eff845753361.png)
2 x 1,21 x 1,652900 = 4.000018 , but it should be rounded to 4.00, not to 4.01

P.D.: I am trying to get an entire number for final price without  using "tax included in price"  option in tax, and I dont want use it for this reason https://github.com/OCA/pos/issues/75#issuecomment-262633504

**Comment by gdgellatly** [comment]
No that is not correct. You are first rounding the ex tax subtotal. Tax
works on either line or overall subtotals rounded to their precision. Then
tax is added.  So 3.31 x 1.21

**Comment by wtaferner** [comment]
@qdp-odoo @nim-odoo @gdgellatly 
As I was thinking about solutions for this issue (global vs. round per line) and I was lately into some fixes of ```compute_all``` where actually all the magic happens, I think it would be possible to put the configuration of round globally/round per line on the tax itself and make the computation therefore consistent and more flexible (not sure why it was never tried though, but I guess it was just not seen as important enough).

This does not resolve the other issue I described and found in https://github.com/odoo/odoo/pull/8427#issuecomment-225200273 but would be a start to finally kind of remove the generic pain (combination of both requirements) for this still not resolved issue.

**What do you think? Would you be ready to help and participate?** 

It could be even implemented in a backward compatible style (even if we have to add a new field) and finally would stop discussions which is probably more valuable than the solution itself for the sake of everyone who is involved or aware of the issue (or not) ;-)

**Comment by gdgellatly** [comment]
You can do it in an addon easily enough. I'll post my supplier tax module
tomorrow for v7 and link it here as example.

**Comment by wtaferner** [comment]
@gdgellatly 
Ok great, in case it is generic enough, although I believe this should be fixed and provided by the core as stated and consistently used over the whole system imho.

I also have done a [module](https://github.com/wt-io-it/odoo-addons/tree/8.0/account_fiscal_position_rounding) which was handling this via fiscal position in v8 but it is not generic enough and there was the overhaul of accounting in v9 as well.

**Comment by nim-odoo** [comment]
It's fixed in master with https://github.com/odoo/odoo/commit/4dcf54e23f8b796396660fd7d4ab33897ef40e12

Since it requires a change in the field type (Monetary -> Float), it was not introduced in v9 or v10.

**Comment by wtaferner** [comment]
@nim-odoo 
True for the already closed issue, but not true for the underlying other issues...sorry for kidnapping the issue a bit, but actually Quentin mentioned the global rounding to be discussed for removal ;-)

**Comment by gdgellatly** [comment]
@wtaferner 

This is our code for rounding per supplier.  It expects round globally set as company policy, but you get the idea, just intercept precision and adjust.

```python
from openerp.osv import orm, fields


class AccountTax(orm.Model):
    _inherit = 'account.tax'

    def check_supplier_tax_precision(self, cr, uid, taxes, partner, precision):
        """

        :param cr:
        :param uid:
        :param taxes: list of tax objects
        :param partner: res.partner object
        :param precision: integer representing rounding precision
        :return:
        """
        if precision is None:
            precision = self.pool['decimal.precision'].precision_get(
                cr, uid, 'Account')
        for tax in taxes:
            if (tax.type_tax_use == 'purchase' and partner and
                    partner.tax_calc_method == 'round_per_line'):
                precision = self.pool['decimal.precision'].precision_get(cr,
                    uid, 'Account')
                break
        return precision

    def compute_inv(self, cr, uid, taxes, price_unit, quantity, product=None,
                    partner=None, precision=None):
        """

        :param cr:
        :param uid:
        :param taxes: list of tax objects
        :param price_unit:
        :param quantity:
        :param product:
        :param partner: res.partner object
        :param precision: integer representing rounding precision
        :return: [ tax ]
            tax = {'name':'', 'amount':0.0, 'account_collected_id':1, 'account_paid_id':2}
            one tax for each tax id in IDS and their children
        """
        precision = self.check_supplier_tax_precision(cr, uid, taxes, partner,
                                                      precision)
        return super(AccountTax, self).compute_inv(
            cr, uid, taxes, price_unit, quantity, product=product,
            partner=partner, precision=precision)

    def _compute(self, cr, uid, taxes, price_unit, quantity, product=None,
                 partner=None, precision=None):
        """

        :param cr:
        :param uid:
        :param taxes: list of tax objects
        :param price_unit:
        :param quantity:
        :param product:
        :param partner: res.partner object
        :param precision: integer representing rounding precision
        :return: [ tax ]
            tax = {'name':'', 'amount':0.0, 'account_collected_id':1, 'account_paid_id':2}
            one tax for each tax id in IDS and their children
        """
        precision = self.check_supplier_tax_precision(cr, uid, taxes, partner,
                                                      precision)
        return super(AccountTax, self)._compute(cr, uid, taxes, price_unit,
            quantity, product=product, partner=partner, precision=precision)


class ResPartner(orm.Model):
    _inherit = "res.partner"

    _columns = {
        'tax_calc_method': fields.selection(
            [('round_per_line', 'Round per Line'),
             ('round_globally', 'Round Globally'), ],
            'Tax Calculation Rounding Method',
            help="If you select 'Round per Line' : for each tax, the tax "
                 "amount will first be computed and rounded for each "
                 "PO/SO/invoice line and then these rounded amounts will be "
                 "summed, leading to the total amount for that tax. If you "
                 "select 'Round Globally': for each tax, the tax amount will "
                 "be computed for each PO/SO/invoice line, then these amounts "
                 "will be summed and eventually this total tax amount will be "
                 "rounded. If you sell with tax included, you should choose "
                 "'Round per line' because you certainly want the sum of your "
                 "tax-included line subtotals to be equal to the total amount "
                 "with taxes."),
        }
```

**Comment by Derter** [comment]
Hello and thanks for participating.

I just wanted to inform you that I updated the odoo code to newest commit and im still facing the exact same issue. That means it is not fixed yet.

**Comment by Derter** [comment]
Addendum: It seems that, when you set 'round per line' rounding Issue is solved. 

We will investigate and update the issue if needed

**Comment by Derter** [comment]
We still have rounding issue after updating the code.
