### ISSUE TITLE
Uncaught Promise > env.services.dialog.closeAll is not a function 

### ISSUE THREAD

**Issue by omar-ms** [odoo/odoo#153020]
**Impacted versions: Odoo 17.0+e-20240205 (Enterprise Edition)**

### Steps to reproduce:

1. Open any app
2. Click on studio icon

### Current behavior:

Odoo Client Error
```
UncaughtPromiseError > TypeError
Uncaught Promise > env.services.dialog.closeAll is not a function
TypeError: env.services.dialog.closeAll is not a function
    at _updateUI (https://xxxxxxx/web/assets/f9ddbc2/web.assets_web.min.js:10182:114)
    at _executeClientAction (https://xxxxxxx/web/assets/f9ddbc2/web.assets_web.min.js:10195:124)
    at async doAction (https://xxxxxxx/web/assets/5440511/web_studio.studio_assets.min.js:168:451)
```

### Expected behavior:
Open app in studio mode

### Screenshot link:
![Screenshot 2024-02-07 125204-1](https://github.com/odoo/odoo/assets/8846492/3dca8a49-fb59-47b0-8ab7-ebaad7d1d8a2)

### Support ticket number submitted via odoo.com/help:
 #3729341

### Referenced code line:
https://github.com/odoo/odoo/blame/b097f20921e40aa4a0152e25c48739deefc4f2e9/addons/web/static/src/webclient/actions/action_service.js#L852

### Referenced commit:
https://github.com/odoo/odoo/commit/8665bf83dd6b024c313437f534a72b0a8867400b

**Comment by michaelhofer-slg** [comment]
We have the same issue, Studio is currently completely unusable for us.

Is there any new on this?

**Comment by tommasotuni** [comment]
Same Issue also for us after upgrading the version

**Comment by jaoa12or** [comment]
Same issue. Is there any solution?

**Comment by lavida-marketing** [comment]
have you activated developer mode before going into Studio?

**Comment by omar-ms** [comment]
> have you activated developer mode before going into Studio?

yes, and still the same error

**Comment by lavida-marketing** [comment]
> > have you activated developer mode before going into Studio?
> 
> yes, and still the same error

ah, i replicated the issue with developer mode deactivated. then Studio worked fine when reactivated

**Comment by omar-ms** [comment]
> > > have you activated developer mode before going into Studio?
> > 
> > 
> > yes, and still the same error
> 
> ah, i replicated the issue with developer mode deactivated. then Studio worked fine when reactivated

Yes I can confirm this, activating the developer mode (with assets) makes the studio work fine.

**Comment by jaoa12or** [comment]
it doesn't work for me

**Comment by omar-ms** [comment]
Hello everyone,

I wanted to provide an update on the issue we encountered with Studio mode errors after updating to Odoo 17.0+e-20240205 (Enterprise Edition). Thanks to the support team's guidance, we have successfully resolved the problem and would like to share the solution for the benefit of the community and anyone else who might face a similar issue.

### Solution:
The issue was effectively resolved by:

**1. Activating Developer Mode**

<img width="260" alt="image" src="https://github.com/odoo/odoo/assets/8846492/0a8f622d-b825-4690-898a-e50991c89fd4">


**2. Regenerating the asset bundles by clicking and the bug icon, then click on _Regenerate Assets Bundles_ from the dropdown.**

<img width="225" alt="image" src="https://github.com/odoo/odoo/assets/8846492/e5e6f2fc-a01f-40cf-bc70-02d58a1134c1">


**3. Clearing the browser cache through developer tools by ensuring the "Disable cache" option was ticked before refreshing the page.**

<img width="226" alt="image" src="https://github.com/odoo/odoo/assets/8846492/ffa6f13b-8914-455a-a0d4-27a8767ed701">


**4. Refresh the page.**


Attempting to bypass the cache using Ctrl + F5 were unsuccessful, but the steps above rectified the problem.

Additionally, it's worth noting that this issue had already been addressed in an enterprise commit 
(https://github.com/odoo/enterprise/commit/e74f777ae2eb2acc7dc1527dacd23e3fe4b434a8), dated January 31, 2024 one week prior to our original update. It appears our setup did not initially reflect this fix, likely due to caching issues.

For those managing Odoo installations, ensuring your enterprise module is up-to-date and following the steps above may prevent or resolve similar issues.

I hope this information helps others facing similar challenges. A big thank you to the Odoo support team, especially Andro, for their assistance in diagnosing and guiding us to a solution.

**Comment by SafwanBackar** [comment]
This issue still persists for me. I tried the method of activating developer mode and opening studio, also the steps provided by omar-ms.

**Comment by Saleh-h-m-abbas** [comment]
> This issue still persists for me. I tried the method of activating developer mode and opening studio, also the steps provided by omar-ms.

Same!

**Comment by EyaChallouf** [comment]
For me, when I checkout the following enterprise commit, it works : e74f777ae2eb2acc7dc1527dacd23e3fe4b434a8

**Comment by MalikAbuShabab** [comment]
> This issue still persists for me. I tried the method of activating developer mode and opening studio, also the steps provided by omar-ms.

Same

**Comment by Innovatecdz** [comment]
> This issue still persists for me. I tried the method of activating developer mode and opening studio, also the steps provided by omar-ms.

same
