### ISSUE TITLE
Bug found in form_relation_widgets.js

### ISSUE THREAD

**Issue by odoo-iventiva** [odoo/odoo#17051]
Impacted versions: 10

Steps to reproduce: 

We found a bug in file web/static/src/js/views/form_relation_widgets.js (V10). The bug consists in that for a model that is read-only and we want to visualise it in a popup, the buttons SAVE and DISCARD still appear in the popup, which is wrong because those buttons should not appear.

In line 156 of form_relation_widgets.js the statement: readonly: !self.can_write always assigns false because self.can_write is evaluated as a string instead of a boolean. It comes as string instead of boolean Please fix this because it is a terrible bug. Or advice if we are wrong. 

Current behaviour: SAVE and DISCARD buttons still appear in form in popup window even if model is set to read only access.

Expected behaviour: SAVE and DISCARD button should not appear. It should only appear the CLOSE button.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hi @odoo-iventiva,

Thank you for your report.
I believe this one is for @ged-odoo. What do you think about this?

Regards,
Yenthe

**Comment by ged-odoo** [comment]
@Yenthe666 @odoo-iventiva this is funny, when you look at https://github.com/odoo/odoo/blob/10.0/addons/web/static/src/js/views/form_common.js#L178,
you see that can_write is set to this.node.attrs.can_write || true.  As far as I know, something || true is true, so this looks like a bug, and a big one (even if it is not a blocking bug: the widget still works). This is weird, because I think I remember that we fixed such a bug recently, but I can't remember exactly.

**Comment by odoo-iventiva** [comment]
Actually because of this bug the widget does not work. If I make a model read only, I still see the buttons SAVE and DISCARD in the popup where model data is shown.

**Comment by celm1990** [comment]
Hi, 
Solutions is change [this lines](https://github.com/odoo/odoo/blob/10.0/addons/web/static/src/js/views/form_common.js#L177) :
this.can_create = this.node.attrs.can_create || true;
this.can_write = this.node.attrs.can_write || true;

By

this.can_create = this.node.attrs.can_create == "false" ? false : true;
this.can_write = this.node.attrs.can_write == "false" ? false : true;

**Comment by Yenthe666** [comment]
@ged-odoo do you agree with the change suggested by @celm1990?
I'm happy to make a PR if you're fine with this.

**Comment by ged-odoo** [comment]
@Yenthe666 yes

**Comment by Yenthe666** [comment]
Okay - will make a PR within the next few days.
