### ISSUE TITLE
[9.0] Incorrect IP address in logs when Odoo is behind proxy

### ISSUE THREAD

**Issue by adekock11** [odoo/odoo#18052]
**Impacted versions:**
9.0

**Steps to reproduce:**
- Deploy Odoo using the official instructions [here](https://www.odoo.com/documentation/9.0/setup/deploy.html) (taking careful look at the Nginx setup)
- After everything is done, make a request to /web/login
- Check the Odoo log files

**Current behavior:**
The log file shows the following data

    2017-07-05 20:07:18,317 22363 INFO mycompany.com werkzeug: 127.0.0.1 - - [05/Jul/2017 20:07:18] "GET /web/login HTTP/1.0" 200 -

Notice that the IP address is 127.0.0.1 and not my IP address.

**Expected behavior:**
Since we are setting `proxy_set_header X-Real-IP $remote_addr;` in the Nginx setup, I would expect the logs to show the real IP address instead of 127.0.0.1, especially since `proxy_mode = True` is set in the Odoo conf file.

**Proposed solution:**
We can change the last lines in `openerp/service/wsgi_server.py` to the following:

    def application(environ, start_response):
        if config['proxy_mode'] and 'HTTP_X_FORWARDED_HOST' in environ:
            werkzeug.serving.WSGIRequestHandler.address_string = lambda self: self.headers.get('x-real-ip', self.client_address[0])
            return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
        else:
            return application_unproxied(environ, start_response)

**Comment by adekock11** [comment]
I see this [pull request](https://github.com/odoo/odoo/pull/59) has the same proposed solution. However I don't quite understand why it was rejected and what is the solution.

**Comment by lukebranch** [comment]
@adekock11 ,

I was running into this issue when trying to track mass mailing clicks, however I found it was due to my Nginx config.

I'll post back shortly with my nginx config.

**Comment by lukebranch** [comment]
https://gist.github.com/lukebranch/4f1c3687877b500c2fe9e2e4cc5a909a
https://gist.github.com/lukebranch/d6e81fb484f2eb5642084d30fc7f707b

I believe it was this line in particular that resolved the issue for me:

https://gist.github.com/lukebranch/d6e81fb484f2eb5642084d30fc7f707b#file-sites-available_example-com-L60

**Comment by adekock11** [comment]
@lukebranch thank you for providing me with this feedback. I'll try the `proxy_redirect off` option. If I understand correctly that was what solved the issue for you.

**Comment by Yenthe666** [comment]
Alright let me now what this gives @adekock11 - if this doesn't fix it I'll ping somebody from Odoo 😉

**Comment by lukebranch** [comment]
@adekock11 ,

No problem. Yes, it's the proxy_redirect off option that did the trick for me. 

For the record i'm just another Odoo user like yourself, no affiliation to Odoo SA, I just thought i'd comment as i've run into this issue in the past.

**Comment by adekock11** [comment]
Hmm no luck. I ended up modifying the `openerp/service/wsgi_server.py` file on our production server. It works perfectly - the only down side of course being that I had to modify Odoo source.

Thanks @lukebranch and @Yenthe666. Hopefully this helps someone in the future.

**Comment by lukebranch** [comment]
@adekock11 ,

Sorry to hear it. Could you post a copy of your nginx config?

**Comment by adekock11** [comment]
@lukebranch, I was thinking over this last night and it's worth mentioning that I'm running Odoo inside a Proxmox container. The container runs on a linux bridge on the subnet `10.0.0.0/24` - the container's IP address is `10.0.0.101` and the gateway is `10.0.0.1`. It's actually the gateway's IP address `10.0.0.1` that displays in the logs and not `127.0.0.1` like I said originally. This adds some complexity to my situation specific as it could be that the networking/routing on my Proxmox host is incorrect.

But since you asked, here is the Nginx config that I currently have **on the Proxmox host** (not on the container itself). I've put proxy_redirect outside `server`, inside `server`, inside `location /`, but the result stays the same.

```
server {
    listen 80;
    server_name ~^.+\.example\.com$;
    return 301 https://$host$request_uri;
}

server {
    listen 443;
    server_name ~^.+\.example\.com$;

    ssl on;
    ssl_certificate /root/example.com.ssl/example.com.crt;
    ssl_certificate_key /root/example.com.ssl/example.com.key;
    ssl_ciphers HIGH:!ADH:!MD5;
    ssl_protocols SSLv3 TLSv1;
    ssl_prefer_server_ciphers on;

    proxy_buffers 16 64k;
    proxy_buffer_size 128k;

    proxy_connect_timeout 600s;
    proxy_send_timeout 600s;
    proxy_read_timeout 600s;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;

    proxy_redirect off;
    proxy_buffering off;

    location / {
        proxy_pass http://10.0.0.101:8069;
    }

    location /longpolling {
        proxy_pass http://10.0.0.101:8072;
    }

    location /web/static/ {
        proxy_cache_valid 200 60m;
        proxy_buffering on;
        expires 864000;
        proxy_pass http://10.0.0.101:8069;
    }
}
```

**Comment by gustavovalverde** [comment]
This seems like an interesting scenario. As I'm also using Odoo instances under this same proxmox scenario. I'll check my nginx configuration and give some feedback here.

**Comment by mrzingo** [comment]
The Proposed solution to change the code only worked for me in odoo 10 ee.

**Comment by adekock11** [comment]
According to [this discussion](https://github.com/odoo/odoo/pull/59), if you use Werkzeug 0.11 and higher, the real IP address should display in the Odoo logs (I haven't confirmed this myself).

The pull request on Werkzeug is [here](https://github.com/pallets/werkzeug/pull/672). I'm using Werkzeug 0.9.6 as per the [requirements.txt on 9.0 branch](https://github.com/odoo/odoo/blob/9.0/requirements.txt#L8).

If we really want to, we may update the requirements.txt on the 9.0 branch, but I'm not sure if that is against the rules of [stable branch](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean).

**Comment by Yenthe666** [comment]
@adekock11 we can update a requirement if there is a good reason for it. Perhaps not against V9 as it doesn't break anything but against 11 should be fine I believe.

**Comment by adekock11** [comment]
I see that on Odoo 11.0 [requirements.txt](https://github.com/odoo/odoo/blob/11.0/requirements.txt#L36) Werkzeug is on version 0.11.15 already, although the rational for changing the version didn't have anything to do with this particular issue. Nevertheless it looks like it has been fixed.

**Comment by Yenthe666** [comment]
So, in conclusion, we can close this bug report? 😉

**Comment by adekock11** [comment]
Sounds good

**Comment by nhomar** [comment]
for future reference.

on odoo.sh (when this issue was published this did not exist) the version for werkzeug is 0.14.1.

![image](https://user-images.githubusercontent.com/338634/36067379-727d9560-0e81-11e8-9fc2-6ef1e6f14f4c.png)

It should be nice if we fix that on the requirements, we lost the on-premise instances with bad requirements and .deb files.

cc @odony

**Comment by ruiztulio** [comment]
Just for the record and in case someone else come across this. 

If you are executing Odoo inside a docker container or a VM behind a proxy this is particullary difficult to debug, but wih werkzeug==0.14.1  and the default nginx configuration for Odoo this is fixed with no major issue or any other change.

**Comment by ananiasfilho** [comment]
Great! 

I Will test and feedback!

**Comment by litnimax** [comment]
I updated to werkzeug 15.0 and now have client ip address in odoo log for .... workers.
Longpolling still shows the address of proxy server.
Does anybody have an idea why?

**Comment by Yajo** [comment]
Interesting, I never realized that. It's probably a different issue, where the longpolling worker doesn't respect the proxy settings. Could you open a new  issue? Thanks @litnimax.

**Comment by litnimax** [comment]
Ok I am opening a new issue.
