### ISSUE TITLE
[10.0]Very big performance issue with onchange

### ISSUE THREAD

**Issue by lmignon** [odoo/odoo#19536]
### Impacted versions:
10.0
### Steps to reproduce:
1/ Install a database with sale_stock module
2/ Initialize some data with this script to run through shell command:

```python
# -*- coding: utf-8 -*-
import logging

_logger = logging.getLogger(__name__)
self = self  # noqa

# Install a language

wizard = self.env['base.language.install'].create({
        'lang': 'fr_BE'
    })
wizard.lang_install()


# Product creation
nb_product = 5000

i = 0

while i < nb_product:
    prod = self.env['product.template'].with_context(
        tracking_disable=True, lang='fr_BE').create({
            'name': 'product_%s' % i,
        })
    i += 1
    if i % 1000 == 0:
        self.env.cr.commit()
        _logger.info("%s Products Created" % i)

# Add a lot of fake translations
cpt = 200000
values = []
cr = self.env.cr
while cpt:
    cpt -= 1
    values.append(
        cr.mogrify(
            "(%s, %s, %s, %s)", (
                'fr_BE',
                'product.template,name',
                'translated',
                '%s' % cpt)
        )
    )
_logger.info('Create %d fake translations' % len(values))
self.env.cr.execute(
    """
    INSERT INTO ir_translation (lang, name, state, value) VALUES
    """ + ','.join(values))
_logger.info('%d fake translations created' % len(values))

# Update stock
i = 0
for product in self.env['product.product'].search([]):
    self.env['stock.quant'].sudo().create({
        'product_id': product.id,
        'location_id': self.env.ref('stock.stock_location_stock').id,
        'qty': 1.0
        })
    i += 1
    if i % 1000 == 0:
        self.env.cr.commit()
        _logger.info("%s Quants Created" % i)
```

3/ / Run the following code through shell command with log_level=debug_sql:

`odoo  shell -d odoo-tmp -c odoo.cfg --log-level=debug_sql < test.py &> log.txt`

This script 
* add a new field `x_product_virtual_available` on `sale.order.line`. This field is a related on `product_id.virtual_available`. (Our users want to see the Forecast quantity on the sale.order.line)
*  simulate a call to  onchange  from the browser on the model `the sale.order` for the field `order_line`. Our so is a new SO with 20 lines.

```python
# -*- coding: utf-8 -*-
import logging
import random
import time

_logger = logging.getLogger(__name__)


partner = self.env.ref('base.res_partner_1')

# create a in memory SO
order_line =[]
sale_order = self.env['sale.order']
so_values = {
    'partner_id': partner.id,
    'partner_invoice_id': partner.id,
    'partner_shipping_id': partner.id,
    'order_line': [],
    'amount_total': 0,
    'amount_tax': 0,
    'amount_untaxed': 0,
    'order_line': order_line
}

original_so = sale_order.new(so_values)
sale_order_line_model_id = self.env['ir.model'].search([('model', '=',
                                              'sale.order.line')])


# add a related on sale.order.line to product_id

if not self.env['ir.model.fields'].search([('name', '=', 'x_product_virtual_available')]):
    self.env['ir.model.fields'].create({
        'name': 'x_product_virtual_available',
        'ttype': 'float',
        'related': 'product_id.virtual_available',
        'required': False,
        'readonly': True,
        'model_id': sale_order_line_model_id.id,
        'store': False,
    })

user_demo = self.env.ref('base.user_demo')
self = self.sudo(user_demo.id).with_context(lang='fr_BE')  # noqa


onchange_specs = sale_order._onchange_spec()
print onchange_specs
onchange_specs['order_line.x_product_virtual_available'] = 0


NB_PRODUCT = 5000
STEP = 20
MAX_LINES =  20

i = 0

while i < MAX_LINES:
    if i % STEP == 0:
        # add lines
        for p in range(STEP):
            x_product_name = 'product_%s' % random.randint(0, NB_PRODUCT)
            p = self.env['product.product'].search([('name', '=', x_product_name)])
            order_line.append(
                (0, 0,
                 {'name': p.name,
                  'product_id': p.id,
                  'product_uom_qty': 2,
                  'product_uom': p.uom_id.id,
                  'price_unit': p.list_price,
                  'x_product_name': '',
                  'price_unit': 10,
                  'price_total': 10,
                  'price_subtotal': 10,
                  'product_uom': self.env.ref('product.product_uom_unit').id})
            )
            # we work on a temporary record

        start_time = time.time()
        res = original_so.onchange(so_values, 'order_line', onchange_specs)
        elapsed_time = time.time() - start_time
        _logger.info('On change with %s lines took %.3f' % (len(
            order_line), elapsed_time))
    i+=1

```

4/ Takes a look into the `log.txt`file .......

### Current behavior:

Our related products on the line are read one by one and the compute of `virtual_available` is also done one by one.

### Expected behavior:

Our related products on the lines are read all at once and the compute of `virtual_available` is done for all the products at once.

For our customer, the screen to create a new sale order becomes unusable beyond about twenty new lines because we have to show him an information that takes 0.5 sec to be computed.This compute is called up for each line and not for all products at once.

**Comment by lmignon** [comment]
OPW-772303

**Comment by lmignon** [comment]
@rco-odoo @xmo-odoo 
### Context
Following the disappointment of users complaining about a very large performance degradation following the migration of Odoo 8 to Odoo 10, I decided to quantify this difference by simulating the behavior of an exchange on a sale order line in Odoo 10 and in Odoo 8 and to measure the time needed in both versions.

In my script I simulate the call to the onchange with 10 new lines on a so. I call the onchange 10 times and after each call, the new lines are saved.  In my script I take care to measure only the time elapsed into the call to onchange method. 

In order to be able to use the same script on both versions, I installed the odoo8-addon-shell module. (Backport of the shell CLI command.) https://pypi.python.org/pypi/odoo8-addon-shell/8.0.1.0.0.99.dev2

Here are the results:

### Odoo 8 

On change with 10 lines (10 new, 0 existing) took 0.013
On change with 20 lines (10 new, 10 existing) took 0.110
On change with 30 lines (10 new, 20 existing) took 0.091
On change with 40 lines (10 new, 30 existing) took 0.101
On change with 50 lines (10 new, 40 existing) took 0.115
On change with 60 lines (10 new, 50 existing) took 0.112
On change with 70 lines (10 new, 60 existing) took 0.124
On change with 80 lines (10 new, 70 existing) took 0.126
On change with 90 lines (10 new, 80 existing) took 0.131
On change with 100 lines (10 new, 90 existing) took 0.135

As can be seen, the time taken remains linear.

### Odoo 10

On change with 10 lines (10 new, 0 existing) took 0.803
On change with 20 lines (10 new, 10 existing) took 1.523
On change with 30 lines (10 new, 20 existing) took 1.893
On change with 40 lines (10 new, 30 existing) took 2.261
On change with 50 lines (10 new, 40 existing) took 2.597
On change with 60 lines (10 new, 50 existing) took 2.978
On change with 70 lines (10 new, 60 existing) took 3.256
On change with 80 lines (10 new, 70 existing) took 3.626
On change with 90 lines (10 new, 80 existing) took 3.936
On change with 100 lines (10 new, 90 existing) took 4.399

In odoo 10, the time required for a call to onchange makes the application unusable. Indeed if you have an so with 30 existing lines, each time you add a new line you must wait at least 2.2 sec...

### Solution

???? We are completely helpless in the face of this problem and we cannot find a workaround. 

### Scripts
Here are the two scipts used to reproduce the problem.
The first one is used to create a lot of products and executed after installing sale_stock on a new db.
The second is executed to reproduce the problem.

init.py

```python
# -*- coding: utf-8 -*-
import logging

_logger = logging.getLogger(__name__)
self = self  # noqa

# Install a language

wizard = self.env['base.language.install'].create({
        'lang': 'fr_BE'
    })
wizard.lang_install()


# Product creation
nb_product = 25000

i = 0

while i < nb_product:
    prod = self.env['product.template'].with_context(
        tracking_disable=True, lang='fr_BE').create({
            'name': 'product_%s' % i,
        })
    i += 1
    if i % 1000 == 0:
        self.env.cr.commit()
        _logger.info("%s Products Created" % i)

# Add a lot of fake translations
cpt = 200000
values = []
cr = self.env.cr
while cpt:
    cpt -= 1
    values.append(
        cr.mogrify(
            "(%s, %s, %s, %s)", (
                'fr_BE',
                'product.template,name',
                'translated',
                '%s' % cpt)
        )
    )
_logger.info('Create %d fake translations' % len(values))
self.env.cr.execute(
    """
    INSERT INTO ir_translation (lang, name, state, value) VALUES
    """ + ','.join(values))
_logger.info('%d fake translations created' % len(values))

# Update stock
i = 0
for product in self.env['product.product'].search([]):
    self.env['stock.quant'].sudo().create({
        'product_id': product.id,
        'location_id': self.env.ref('stock.stock_location_stock').id,
        'qty': 1.0
        })
    i += 1
    if i % 1000 == 0:
        self.env.cr.commit()
        _logger.info("%s Quants Created" % i)
```

test.py

```python
import logging
import random
import time

_logger = logging.getLogger(__name__)


partner = self.env.ref('base.res_partner_1')

sale_order_line_model_id = self.env['ir.model'].search([('model', '=',
                                              'sale.order.line')])


# add a related on sale.order.line to product_id

if not self.env['ir.model.fields'].search([('name', '=', 'x_product_virtual_available')]):
    self.env['ir.model.fields'].create({
        'name': 'x_product_virtual_available',
        'ttype': 'float',
        'related': 'product_id.virtual_available',
        'required': False,
        'readonly': True,
        'model_id': sale_order_line_model_id.id,
        'store': False,
    })


if not self.env['ir.model.fields'].search([('name', '=', 'x_product_default_code')]):
    self.env['ir.model.fields'].create({
        'name': 'x_product_default_code',
        'ttype': 'char',
        'related': 'product_id.default_code',
        'required': False,
        'readonly': True,
        'model_id': sale_order_line_model_id.id,
        'store': False,
    })

sale_order = self.env['sale.order']
onchange_specs = sale_order._onchange_spec()
print(onchange_specs)
onchange_specs['order_line.x_product_virtual_available'] = 0
onchange_specs['order_line.x_product_default_code'] = 0

NB_PRODUCT = 25000
STEP = 10
MAX_LINES =  100
i = 0

existing_lines = []
so_values = {
   'partner_id': partner.id,
   'partner_invoice_id': partner.id,
   'partner_shipping_id': partner.id,
   'order_line': [],
   'amount_total': 0,
   'amount_tax': 0,
   'amount_untaxed': 0,
}
so = self.env['sale.order'].create(so_values)

while i < MAX_LINES:
    if i % STEP == 0:
        # add lines
        new_lines = []
        selected_p = set()
        for p in range(STEP):
            # be sure to get different product
            rand_p = random.randint(0, NB_PRODUCT)
            while rand_p in selected_p:
                rand_p = random.randint(0, NB_PRODUCT)
            selected_p.add(rand_p)
            x_product_name = 'product_%s' % p #random.randint(0, NB_PRODUCT)
            pr = self.env['product.product'].search([('name', '=', x_product_name)])
            o_v ={'name': pr.name,
                  'order_id': so.id,
                  'product_id': pr.id,
                  'product_uom_qty': 2,
                  'product_uom': pr.uom_id.id,
                  'price_unit': pr.list_price,
                  'price_unit': 10,
                  'product_uom': self.env.ref('product.product_uom_unit').id}   
            new_lines.append((0, 0, o_v))
        order_line = existing_lines + new_lines
        # try to be into the same state as when 
        # the onchange method is called from the UI
        self.env.reset()
        # we work on a temporary record
        #logging.getLogger('odoo.sql_db').setLevel(logging.DEBUG)
        #logging.getLogger('openerp.sql_db').setLevel(logging.DEBUG)
        # create a in memory SO
        
        sale_order = self.env['sale.order']
        so_values = {
           'id': so.id,
           'partner_id': partner.id,
           'partner_invoice_id': partner.id,
           'partner_shipping_id': partner.id,
           'order_line': [],
           'amount_total': 0,
           'amount_tax': 0,
           'amount_untaxed': 0,
           'order_line': order_line
        }

        # uncomment these lines to activate the sql debug only for queries
        # done in onchange
        #self.env.cr.sql_log = True
        #logging.getLogger('odoo.sql_db').setLevel(logging.DEBUG)
        #logging.getLogger('openerp.sql_db').setLevel(logging.DEBUG)
        start_time = time.time()
        res = so.onchange(so_values, 'order_line', onchange_specs)
        elapsed_time = time.time() - start_time
        count = len(order_line)
        _logger.info('On change with %s lines (%d new, %d existing) took %.3f' % (count, len(new_lines), len(existing_lines), elapsed_time))

        # create new lines
        for m, n, v in new_lines:
            sol = self.env['sale.order.line'].create(v)
            existing_lines.append((4,sol.id, False))
    i+=1
```

**Comment by Yenthe666** [comment]
@odony and @mart-e this is relevant for you too. Perhaps we could pick this up after Odoo Experience? The benchmarks show a huge difference in performance.

**Comment by rco-odoo** [comment]
@lmignon the problem should be fixed now.

For the record, here are the timings I measured before the fix:

    On change with 10 lines (10 new, 0 existing) took 0.504
    On change with 20 lines (10 new, 10 existing) took 0.996
    On change with 30 lines (10 new, 20 existing) took 1.206
    On change with 40 lines (10 new, 30 existing) took 1.440
    On change with 50 lines (10 new, 40 existing) took 1.646
    On change with 60 lines (10 new, 50 existing) took 1.884
    On change with 70 lines (10 new, 60 existing) took 2.164
    On change with 80 lines (10 new, 70 existing) took 2.396
    On change with 90 lines (10 new, 80 existing) took 2.624
    On change with 100 lines (10 new, 90 existing) took 2.920

and after the fix:

    On change with 10 lines (10 new, 0 existing) took 0.212
    On change with 20 lines (10 new, 10 existing) took 0.259
    On change with 30 lines (10 new, 20 existing) took 0.276
    On change with 40 lines (10 new, 30 existing) took 0.300
    On change with 50 lines (10 new, 40 existing) took 0.337
    On change with 60 lines (10 new, 50 existing) took 0.376
    On change with 70 lines (10 new, 60 existing) took 0.444
    On change with 80 lines (10 new, 70 existing) took 0.469
    On change with 90 lines (10 new, 80 existing) took 0.402
    On change with 100 lines (10 new, 90 existing) took 0.459

**Comment by rco-odoo** [comment]
@lmignon by the way, thanks for the scripts. I really made my job easier for finding the root cause of the problem!

**Comment by Cedric-Pigeon** [comment]
@rco-odoo 

Unfortunatly, it seems that the fix is not enough. I deployed it on production and the onchange time still increase.
For a sale order with 150 lines it takes more than 15 sec per lines.

**Comment by rco-odoo** [comment]
@Cedric-Pigeon @lmignon I have found a prefetching issue in related fields. In your use case, the target of the related field (`virtual_available` on `product.product`) was never computed in batch. I rewrote the computation of related fields in order to fix this #20017.

**Comment by sbidoul** [comment]
@rco-odoo cool! Does this bring the test script to near constant time as in v8?

**Comment by rco-odoo** [comment]
@sbidoul alas no, it does not fix all performance issues in this case. But it's another step forward. I will keep analysing what the test script shows.

**Comment by lmignon** [comment]
@rco-odoo Thank you for your work. @Cedric-Pigeon will test your change and give you some feedback.

**Comment by lmignon** [comment]
@rco-odoo Thanks to your fixes, the performances are better but don't allow our client to use Odoo to create sale orders with 200 lines. In our case, if we add one line, the onchange takes 14 seconds. Thanks to pyflame we have discovered the last bottlenecks and we are able to reduce the time spent to 3 seconds. Our fixes are stranges and are a way to force the prefetch in cases where we expect it should be done by the framework.
The context is the following.
1. Into the call to onchange
2. records.mapped('orderline.my_computed_field')
3. into the function `def _compute_my_omputed_field`, the prefetch of products is not done when we iter on the lines and  we access to a related field on product_id defined into product.template into the loop.
```python
class OrderLine():

    def _compute_my_computed_field,
        for line in self:
            line.my_computed_field = line.product_id.type
```
If I summarize, the prefetch is lost when the compute_related is called for inherited field.  The workaround is to call `self.mapped('product_id.type`) before the loop.
We try to write a script to reproduce the problem without success at the moment.

lmi

**Comment by Cedric-Pigeon** [comment]
@rco-odoo We also noticed that the filtered function breaks the prefetch due a browse as return:
https://github.com/odoo/odoo/blob/10.0/odoo/models.py#L4994

By changing this lines to :
```python
self.browse([rec.id for rec in self if func(rec)], prefetch=self._prefetch)
```
The response time of the onchange is divided by 3 in our case.

**Comment by rco-odoo** [comment]
@Cedric-Pigeon the method `filtered` breaks the prefetch **on purpose**: use `filtered` to restrict yourself to a subset of records, and therefore do not expect the whole set to be prefetched.  This semantics is used in some places in Odoo, so don't modify it globally by patching the ORM.  Instead, use `with_prefetch` explicitly in the business code where you want to keep the prefetching object.

**Comment by rco-odoo** [comment]
@Cedric-Pigeon note that your change may make some code faster (because more prefetching) and other code slower (because too much prefetching).

**Comment by Cedric-Pigeon** [comment]
@rco-odoo Thanks for the tips. It works. It just left the problem of mapped pointed by @lmignon

**Comment by rco-odoo** [comment]
@Cedric-Pigeon which call to `filtered` did you modify? If it is in our code, I would be glad to fix it.

**Comment by Cedric-Pigeon** [comment]
@rco-odoo I changed some on custom code. But it would be glad if you could rework this method:
https://github.com/odoo/odoo/blob/10.0/addons/sale_stock/models/sale_order.py#L111

The super is called in a loop preventing a work by batch.
Rewriting like this is much better and strongly improves performances on huge databases:
```python
to_recompute = self.filtered(lambda x: x.product_id.type not in (
            'consu', 'product')).with_pefetch(self._prefetch)
super(SaleOrderLine, to_recompute)._compute_qty_delivered_updateable()
for line in self - to_recompute:
    line.qty_delivered_updateable = False
```

**Comment by rco-odoo** [comment]
@lmignon I am curious about that one, because 10412d351cc4ba66ff4d10879d22535fc4e3e222 should have fixed it. I basically reimplemented the computation of related fields following the same approach as `mapped`'s implementation: one field at a time on all records. It should guarantee optimal prefetching on every field access. I was able to observe the impact: it makes fields computed in batch instead of one-by-one, and fields are also fetched in batch.

**Comment by Cedric-Pigeon** [comment]
@rco-odoo To be complete to have a good prefetching on this sale method, we had to add 
```python
self.mapped('product_id')
```
before the filtered line. Otherwise the prefetching is not good.

As a measure, with all these points,  an onchange on a so with 230 lines failed from 15,2 sec to 2.4 sec.

**Comment by rco-odoo** [comment]
@Cedric-Pigeon I guess you meant "**falled** from 15,2 sec to 2.4 sec" :smiley:

**Comment by Cedric-Pigeon** [comment]
@rco-odoo Keyboard issue ;-)

**Comment by rco-odoo** [comment]
I propose to rewrite the method as follows. Can you confirm it works well?
```python
@api.depends('product_id')
def _compute_qty_delivered_updateable(self):
    # prefetch field before filtering
    self.mapped('product_id')
    # on consumable or stockable products, qty_delivered_updateable defaults
    # to False; on other lines use the original computation
    lines = self.filtered(lambda line: line.product_id.type not in ('consu', 'product'))
    lines = lines.with_prefetch(self._prefetch)
    super(SaleOrderLine, lines)._compute_qty_delivered_updateable()
```

**Comment by Cedric-Pigeon** [comment]
@rco-odoo I have a doubt. What about the else condition ?

**Comment by rco-odoo** [comment]
@Cedric-Pigeon computed fields are always initialized to `False` before calling their compute method. That's why the loop that assigns to `False` is redundant.

**Comment by Cedric-Pigeon** [comment]
@rco-odoo Great for me than. I tested and performances are really good.

**Comment by rco-odoo** [comment]
@Cedric-Pigeon I made a branch with the proposed rewrite, and will merge it as soon as the runbot confirms nothing is broken.  Thanks a lot for spotting this badly written method!

**Comment by pedrobaeza** [comment]
The `self.mapped('product_id')` shouldn't be done also on original method on `sale` module when you don't have sale_stock installed?

Thanks any way for the good "live" performance session.

**Comment by rco-odoo** [comment]
@pedrobaeza I was thinking about that one, too. But that would mean that prefetching does not work so well...

**Comment by rco-odoo** [comment]
@Cedric-Pigeon I could not reproduce the prefetching issue in `_compute_qty_delivered_updateable`. I tried @lmignon's test file, after making half the products of type 'service', but the timings remain the same.

**Comment by lmignon** [comment]
@rco-odoo Unfortunately, I'm not surprised. We can't understand how we get there.  In in some weird conditions when we traverse a relation to get access to a field inherited from 'inherits' (line.product_id.type)
the call to `record._in_cache_without(self)` https://github.com/odoo/odoo/blob/10.0/odoo/fields.py#L1020 return only one records... :cry:

**Comment by Cedric-Pigeon** [comment]
@rco-odoo Did you create a PR for the sale method refactoring ? I can't find it out.

**Comment by Cedric-Pigeon** [comment]
ping @rco-odoo
