### ISSUE TITLE
[10.0] Field values not translatable: On calendar meeting edition

### ISSUE THREAD

**Issue by khishigbat** [odoo/odoo#20634]
Impacted versions: 10.0

Steps to reproduce:
Calendar -> Create and edit a meeting

Current behavior:
The terms "Customer Meeting, Internal Meeting, ..." for field "**Tags**";
"15 Minutes(s), 30 Minutes(s), ..." for field "**Reminders**"  are not translatable. I can't find them on Transifex, nor in Translated Terms.

Expected behavior:
The above terms to become able to be translated.

Video/Screenshot link (optional):
![1](https://user-images.githubusercontent.com/29530738/32308294-1f8f1d84-bfc0-11e7-9dfd-a58e66f5eb8d.png)
![2](https://user-images.githubusercontent.com/29530738/32308297-2372269e-bfc0-11e7-9d1d-d778d7165be7.png)
![translated terms](https://user-images.githubusercontent.com/29530738/32308302-2755572c-bfc0-11e7-8bfe-0d95443bd35a.png)

**Comment by mart-e** [comment]
Hello,

For the meeting tags, I disagree. Actually it should not be as data as it is business relevant.
You can go to Settings > Technical > Calendar > Meeting Types to change it.
I have moved them from data to demo data in master at 42a402bf0ec788667c1bd6d8a3c378ec8f7cd41f

In 11.0, I can accept as an improvement, to put the name of the reminders as translatable as this one is useful to have as a data.
Done at 36caadaf6a8c73eb0de6bdc44fb09adb75b96707

**Comment by khishigbat** [comment]
Thank you very much! @mart-e

**Comment by khishigbat** [comment]
Hello @mart-e 

I'm sorry to bother you, but the strings "1 Day(s); 1 Hour(s); 15 Minute(s); 2 Hour(s); 3 Hour(s), by email; 30 Minute(s); 6 Hour(s), by email" are still not on Transifex.

**Comment by mart-e** [comment]
@khishigbat it should now
![screenshot-2017-11-16 odoo 11 0 transifex editor](https://user-images.githubusercontent.com/564822/32885178-06ab88a4-cabd-11e7-85da-a65c58bffd06.png)

**Comment by khishigbat** [comment]
@mart-e perhaps not on mongolian 
![mn](https://user-images.githubusercontent.com/29530738/32886837-f3a968ee-cafc-11e7-8fdb-fd58d3df3f8a.png)

**Comment by mart-e** [comment]
@khishigbat I don't know which project you are checking, but not the v11 as the Mongolian was in the list of languages. I have added Mongolian to the list of languages for v11.

**Comment by khishigbat** [comment]
@mart-e it's v10.0

**Comment by khishigbat** [comment]
https://www.transifex.com/odoo/odoo-10/translate/#mn/calendar?translated=no

**Comment by mart-e** [comment]
As said previously, the change was made in v11, not v10.
V10 is a stable version where we only accept bug fixes, this one is an improvement.
As v11 is just released, we still tolerate some improvements so I have changed it there but this kind of changes usually targets the master branch.

**Comment by khishigbat** [comment]
I'm so sorry for misunderstanding.
We understand. Please forgive me for wasting your time. :(

**Comment by mart-e** [comment]
No problem, thanks for your help to translate Odoo :)
