### ISSUE TITLE
Inconsistent and incorrect behaviour of taxes when no product is set on invoice, also applies to sale and purchase

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#20636]
Impacted versions: 11.0 but I imagine it goes back.
Firstly apologies if this is a duplicate, there were 200 odd issues with tax in them, I went back as far as March.

Steps to reproduce:
Setup:
As a multicompany user.

- In a multicompany environment, set multiple taxes on the sales account (i.e. account.account income in product category), 1 for each company and no taxes on the product.
- For sake of explanation lets say Company A and Company B with 1 sales tax each.
- Without entering the product, set the account on the invoice line.
  - 2 taxes appear.
- Enter the product
  - Only the correcttax for the correct company appears.

This is because set_taxes correctly filters taxes whereas _onchange_account_id does not.

This override fixes it for me
```python
class AccountInvoiceLine(models.Model):
    _inherit = 'account.invoice.line'

    @api.onchange('account_id')
    def _onchange_account_id(self):
        super(AccountInvoiceLine, self)._onchange_account_id()
        if not self.product_id and self.account_id:
            company_id = self.company_id or self.env.user.company_id
            self.invoice_line_tax_ids = self.invoice_line_tax_ids.filtered(
                lambda r: r.company_id == company_id)
```

Now for sales and purchases the issue is slightly different.  Using the same setup enter a product on either a sale order or purchase.

- No taxes.
This is because the sales and purchase orders take no account of the assigned account.

Again I wrote some stupid code to fix which aligns the tax selection for all 4 use cases to be identical to the single (almost) correct one (a product on an invoice).  It is here, but is really a patch rather than what would ever be merged.  https://github.com/odoonz/odoonz-addons/blob/11.0/tax_from_account/models/tax_from_account.py

Note the final bug, which you will see differs from set_taxes is a corner case, but a really important and common one.  Where a single company user sets a tax on a product or creates a product it can cause chaos for other companies.  This is why I filter product taxes and if that is empty then filter account taxes, rather than filtering after.

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
Hmm @qdp-odoo I believe there are some genuine issues here 😉

**Comment by oco-odoo** [comment]
@gdgellatly The problem is actually here that you should not be able set taxes belonging to other companies than the account's. This bug is pretty old, I just fixed it in 9.0, here https://github.com/odoo/odoo/commit/d1377650da966bde192195e3e892d9d4be21b8f3 , by simply adding a domain on the field. Thank you for reporting the issue !

**Comment by gdgellatly** [comment]
@oco-odoo that only fixes the issue for invoices, not sales and purchases.

**Comment by oco-odoo** [comment]
@gdgellatly In your original message, you mention that, in order to create each of the bugs you report, you have to  link taxes from different companies to the same account. As I told you, this is what is wrong in the first place (as an account always belongs to a single company), so the fix forbids that. So, yes, I'm sure; unless I misunderstood you, in which case I need clearer explanations ;)

**Comment by gdgellatly** [comment]
@oco-odoo sorry hard to remember everything months after the fact and was working on mobile phone yesterday.  Yes that may solve the problem for the invoice case, although realistically it should be a constraint rather than just enforced in a view.

However it doesn't resolve the inconsistency issue for sales and purchases.  The sale and purchase issue happens irrespective of what taxes are set on the account.  The bug report was primarily about the inconsistent behaviour.  e.g. If I set a tax on an account, that same tax should display on the sale and the invoice, or the purchase and the invoice respectively.  The current behaviour is inconsistent, as sales and purchase do not even look at the product accounts to get taxes, but rely on the product, whereas the invoice does.

Or put another way, sales orders and purchase orders should use the taxes in the same way was invoices do.  Currently, you need to assign the same taxes to both the product and account which in general use leads to all sorts of errors especially in a multicompany environment.

**Comment by oco-odoo** [comment]
Master bug created https://www.odoo.com/web#id=1825772&view_type=form&model=project.task&action=333&active_id=1278&menu_id=4720.

@gdgellatly Indeed, you are right. Thank you for reporting the issue; we'll work on a fix for this ;)

**Comment by oco-odoo** [comment]
@gdgellatly It got cancelled by @nim-odoo , for the following reason (I'm quoting his message):

 "To me this should not be changed. On the invoice, the account is set directly on the model (self.account_id): https://github.com/odoo/odoo/blob/9.0/addons/account/models/account_invoice.py#L1174-L1177

For SO and PO, you have to go through the product configuration to get the account and expect these are correct... I think this is out of scope, and could actually be harmful. From one day to another, you'd have default taxes set on SO and PO while you would not expect it."

**Comment by gdgellatly** [comment]
@nim-odoo I think your reasoning is wrong here.  \cc @qdp-odoo 

Sure there is no account_id on SO and PO, therefore the invoice will be incorrect when created from these.  Moreover it leads to a more complex and tedious configuration than necessary.

By not fixing this:
All products must be setup with correct taxes - lets assume that nr. of products is > nr. accounts by orders of magnitude.  e.g. 10,000's vs 100's and in fact IRT products the nr. of accounts is 10's.
When a global change happens - e.g. new VAT rate, all products require updating.
All users setting up products must have access to accounting for ALL companies, otherwise products are setup without taxes for those companies.
It makes the entire product_id_change on invoices pointless if it gives a different result to SO's.
All product accounts must also be setup (mostly).
Any error and you have PO's and SO's that differ from their invoice if any edit is made to a line, moreover you have invoices created manually that differ from invoices created from SO and PO.

Therefore rather than the claim of having differing default taxes from one day to another where you don't expect (a strange claim, given far less users generally have account than product write access, and products change far more than accounts), I can promise you, in a multicompany environment you have issues EVERY day when users create products.

By fixing this you can have a very simple configuration - indeed you could almost delete the taxes on products entirely.  Just set taxes on the accounts, for those rare exceptions set it on the product.
