### ISSUE TITLE
Cannot Start Odoo Server Services 

### ISSUE THREAD

**Issue by rovilstretchsense** [odoo/odoo#20715]
Impacted versions: Odoo 11

Steps to reproduce:

Current behavior:

Expected behavior:

Video/Screenshot link (optional):

![capture](https://user-images.githubusercontent.com/33413538/32430649-0ca5cd94-c335-11e7-967a-eb16fe73bf9a.PNG)

**Comment by andreassalix** [comment]
Any news on this? Have same issue. Any log files I can check?

**Comment by skanel** [comment]
I got the same error.

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo.com/runbot), so please be sure you are following the proper installation instructions. Check them on https://www.odoo.com/documentation/11.0/setup/install.html.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Comment by oJamie** [comment]
Hi, 

It seems like the Odoo-server and PostgreSQL are both disabled. To fix this, you will need to go to your system service and check the properties for the Odoo-server. Set it to automatic and navigate to the PostgreSQL and as well, check if the properties are disabled then set to automatic. Then restart your Odoo-server.
The problem should be solved.

**Comment by lthieu1123** [comment]
Hi, I still face the same issue when running odoo-server 12 on windows 10 and windows 7.
