### ISSUE TITLE
odoo11 stock have a  server error

### ISSUE THREAD

**Issue by 423230557** [odoo/odoo#20784]
Impacted versions:Odoo 11.0+e-20171005

Steps to reproduce: i purchase 4934 , my stock is more than 4934

Current behavior: reserved stock:3623    on hand stock:4934    i want sale this stock, but it remind me error:
it is not possible to unreserve more products than you have in stock. 

Expected behavior: how to sale this?  how to solve it 

Video/Screenshot link (optional):

**Comment by sle-odoo** [comment]
Hi,
We have fixed multiple points that could trigger this issue recently, could you please uprade your Odoo version?
Also, are you using multiple UOM? 
Did you change the type of your product from stockable to consumable (or the other way)?
Did you run an inventory adjustment to decrease the quantity while moves were reserved?

Fixing this issue without debugger could take a while, would you consider sending me a backup of your database?

Regards

**Comment by haconsult** [comment]
Hi,
I have the same issue. By trying to track it down I found a strange rounding behavior. I did the following:

- Fresh database, install Sales, Purchase and a Localization (German in my case)

- Create one Vendor and one Customer

- Create a stockable product

- Purchase 1.000 units of the product, receive products, validate

- Check inventory, you have 1.00 units in stock - good.

- Sell 1.100 units of the product. 

- Ship products, validate with or without backorder

- Check the delivery order: Initial demand has changed to 0.999 (expected: 1.000). Demand of the backorder (or the canceled second delivery order in case you did not produce a backorder) is 0.101 (expected: 0.100)

Maybe this is related to the issue first described.
Regards

**Comment by haconsult** [comment]
Another (related?) issue with the inventory:

- Same as above: fresh db, Purchase, Sales and Localization installed, 1 Vendor 1 Customer, 1 stockable Product

- Purchase 1.000 units of the product, receive goods, validate

- Check inventory: 1.000 products on hand, as expected

- Check inventory at a specific date (now): no products on hand :(

**Comment by haconsult** [comment]
Another (related?) issue with the inventory:

- Same as above: fresh db, Purchase, Sales and Localization installed, 1 Vendor 1 Customer, 1 stockable Product

- Purchase 1.000 units of the product, receive goods, validate

- Check inventory: 1.000 products on hand, as expected

- Check inventory at a specific date (now): no products on hand :(

**Comment by amoyaux** [comment]
Hey,

I did two fixes. one for each problem. Should be resolve soon.

Sincerely, thanks for reporting

**Comment by Yenthe666** [comment]
@amoyaux I believe you're talking about https://github.com/odoo/odoo/commit/6b7ac1c5d71f8d18da68040e6035a2af8eca71e2 and https://github.com/odoo/odoo/commit/8900dc22048d460b44b6b308f88f2737cac5b4ba right? Thanks for the fixes. 😉

**Comment by amoyaux** [comment]
@Yenthe666  Yep Sorry forgot to post it here. Thanks for your help.

**Comment by haconsult** [comment]
Hi,
Thanks for your fix! The test setup as described works fine now.

However, in my production db I still face the 
**"it is not possible to unreserve more products than you have in stock"**
issue. 
Sometimes it happens that the reserved amount differs from the amount in the sales order. One example:

- I have 3.420 units on hand
- Sell 1.402 units
- Validate sales order
- 1.4020000000000001 units are reserved
- Impossible to validate delivery order with error "it is not possible to unreserve more products than you have in stock"

It happens with some sale orders but not all. I have no idea what triggers this behavior.

**Comment by haconsult** [comment]
Ok, by chance I found a way to reproduce:

- fresh db, just like above
- purchase 18.46 units, validate incoming delivry
- check quantity on hand, 18.46 - perfect
- create a sales order with two lines of the same product: 0.472 units and 0.412 units
- create delivery order, check reserved quantities: 0.47200000000000003 and 0.41200000000000003
- impossible to validate this delivery order because "it is not possible to unreserve more products than you have in stock"

**Comment by amoyaux** [comment]
@haconsult Gonna check for this.

**Comment by amoyaux** [comment]
@haconsult Should be resolved with commit https://github.com/odoo/odoo/commit/6b3fefcdbbf58c8a6284b0b5b4f71b77c5cfeb02

**Comment by haconsult** [comment]
@amoyaux 
Thanks for the fix. Seems to work, the "unreserve" issue is gone.
However, the system still reserves the odd amounts of products (0.47200000000000003 and 0.41200000000000003). See images. I do not know if this is an issue since it is now possible to unreserve / deliver the goods as intended.

Thanks again and best regards.
![screenshot_20171121_182930](https://user-images.githubusercontent.com/29736794/33087250-53c97214-ceea-11e7-9099-5337ae03836c.png)
![screenshot_20171121_183011](https://user-images.githubusercontent.com/29736794/33087251-53f8d1bc-ceea-11e7-8e10-3aa91219787e.png)

**Comment by amoyaux** [comment]
@haconsult Yep it seems my patch does not correct this display issue. You should not have any issue with reservation anymore. However this values is not friendly user thus I'm also gonna fix it.

**Comment by lukebranch** [comment]
@amoyaux ,

Not sure if I should create a new issue for this, however i'm encountering the same error message related to another flow.

<h1>Impacted Versions</h1>
11.0 Community
11.0 Enterprise

<h1>Steps to Reproduce:</h1>

1. Setup product with tracking by Lot
2. Purchase and Receive Product (eg. receive 100 Units with one lot number)
3. Sell Product (eg. 100 Units from a single lot) and attempt to create a 'packing list' (eg. split 50 Units into one pack, and 50 Units into another pack using 'Put in Pack' method - add 50 Units to done related to a lot > save > Put in Pack, then add another 50 Units to done in the wizard and then save and Put in Pack - you will have two lines with 50 units in reserved and 50 units in done at this stage - see screenshot for reference):
<img src="https://user-images.githubusercontent.com/2337666/33205353-9b3ba870-d141-11e7-8df3-b347f660a6e1.png"/>
4. Try to validate this picking
5. Error: It is not possible to unreserve more products of than you have in stock.

<h1>Current Behaviour:</h1>
Can't create a 'packing list' (this is used for outgoing shipments for import/export/trading companies) for outgoing shipments in Odoo.

<h1>Expected Behaviour:</h1>
You can create a simple 'packing list' using this method like you can in version 10.0.

<h1>Video/Screenshot/Link:</h1>

**Comment by sle-odoo** [comment]
@lukebranch this issue is fixed in rev https://github.com/odoo/odoo/pull/21175/commits/e307fe8d2909a297c193b3694183cf1411b9970a

i'll write a test and merge it in 11.0 very soon
thanks for your report

**Comment by lukebranch** [comment]
@sle-odoo ,

Thanks for the incredibly quick response!

I will patch my local dev now and test.

**Comment by 423230557** [comment]
Setting When to reserve sold products: Manually or based on automatic scheduler    ,now  everything is good,

**Comment by ginogervasio** [comment]
Hi,

It seems that this issue has already been resolved but I am still encountering the error.

### Version

- Odoo.com (11.0)

### Steps to reproduce

1. Created and confirmed a sales quotation
2. Processed the delivery and checked availability.
3. Can't unreserve the order because of the error
![bug_unreserving_error](https://user-images.githubusercontent.com/192583/45669109-8735df80-bb51-11e8-8b30-7d23668bda1d.gif)
