### ISSUE TITLE
[BUG][11.0] web : binary field return a string during an onchange.

### ISSUE THREAD

**Issue by fmdl** [odoo/odoo#22282]
Sorry @Yenthe666, @Elkasitu, the issue https://github.com/odoo/odoo/issues/22231 seems not finish

**Impacted versions:**
V11

**Steps to reproduce:**

-Create a binary field `an_binary` and other field `an_integer`
-Add `an_binary` and `an_integer`  in a view
-Add this code in python code
```
@api.onchange('an_integer')
def onchange_integer(self):
    print(self.an_binary)
```
Then
-Create a new record
-Add a file in `an_binary`
-Add a value in `an_integer`
-You see in log the file en base64 --> it is OK
-Save record
-Edit record
-Change value in `an_integer`
-You see in log `xxx bytes` --> Wrong

**Comment by celm1990** [comment]
I get same error.
Upgrade today from github repo and work fine now

**Comment by fmdl** [comment]
I have find the issue with the last repo.

**Comment by Elkasitu** [comment]
I'm not sure this is a bug _per se_, your onchange shouldn't depend on the value of self.an_binary, **since this value can change depending on whether or not `bin_size: True` was passed in the context**

https://github.com/odoo/odoo/blob/bd760f074688fd92c96fd75ec33231bb9c3e7eff/odoo/fields.py#L1666-L1676

You should explicitly set `bin_size` to `False` before accessing `an_binary` with a call to `with_context` in order to get the proper binary value, however I'm not sure how well this would work inside an onchange...

@alexkuhn maybe there's a leftover bin_size: true from your commits? if not, disregard

**Comment by alexkuhn** [comment]
I think this is the correct behaviour: when you add a file in `an_binary`, it is represented client-side in base64, so that the server gets the correct value for the binary field when you write on the record.

When you save the changes, it reads again the record from the server, and since any fetch of records has `{bin_size: true}` in the context, the binary is represented by its size.

https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/views/basic/basic_model.js#L1857

@Elkasitu is correct, in that you should explicitly set `bin_size` to `False` server-side in order to read the data (and not the binary size).

I also find it confusing that, when reading a binary field from the server, it passes by the method `convert_to_cache`, and the comments tell that the special treatment about `bin_size` assumes that the request comes from the client, which is not the case here...

**Comment by fmdl** [comment]
@alexkuhn @Elkasitu @Yenthe666  I have made some more test, and some things is wrong.

**Test 1**
-Create a binary field `an_binary` and other field `an_integer`
-Add `an_binary` and `an_integer`  in a view
-Add this code in python code
```
@api.onchange('an_integer')
def onchange_integer(self):
    print(self.an_binary)
```
Then
-Create a new record
-Add a file in `an_binary`
-Add a value in `an_integer`
-You see in log the file en base64 --> it is OK
-Save record
-Edit record
-Change value in `an_integer`
-You see in log `xxx bytes` --> Wrong

**Test 2 {'bin_size':True}**
```
@api.onchange('an_integer')
def onchange_integer(self):
    print(self.with_context({'bin_size':True}).an_binary)
```
Then
-Create a new record
-Add a file in `an_binary`
-Add a value in `an_integer`
-You see in log `False` --> Wrong
-Save record
-Edit record
-Change value in `an_integer`
-You see in log `False` --> Wrong

**Test 2 {'bin_size':False}**
```
@api.onchange('an_integer')
def onchange_integer(self):
    print(self.with_context({'bin_size':False}).an_binary)
```
Then
-Create a new record
-Add a file in `an_binary`
-Add a value in `an_integer`
-You see in log `False` --> Wrong
-Save record
-Edit record
-Change value in `an_integer`
-You see in log `False` --> Wrong

**Comment by fmdl** [comment]
Question: some one work on this issue ?

Thanks

**Comment by KasperDeclercq** [comment]
I tried it a few days ago with the latest version and my problem (Using a binary  field in a TransientModel) was fixed.

**Comment by alexkuhn** [comment]
@rco-odoo Could you please have a look at this issue?

There are some server-side issues with binary fields with `bin_size`. When the server reads a field, it calls this code and wrongly assumes that it comes from the web_client:

https://github.com/odoo/odoo/blob/bd760f074688fd92c96fd75ec33231bb9c3e7eff/odoo/fields.py#L1666-L1676

The weird behaviour of the tests from @fmdl are still present in v11, as shown in the following short clips:

**Test 1**
   ```
@api.onchange('an_integer')
def onchange_integer(self):
    print(self.an_binary)
   ```
https://youtu.be/GVKaqSS86LI

**Test 2**
```
@api.onchange('an_integer')
def onchange_integer(self):
    print(self.with_context(bin_size=True).an_binary)
```
https://youtu.be/gKkC94HdraY

**Test 3**
```
@api.onchange('an_integer')
def onchange_integer(self):
    print(self.with_context(bin_size=False).an_binary)
```
https://youtu.be/CRrZgdUNIN8

**Comment by fmdl** [comment]
OPW-1834876

**Comment by nim-odoo** [comment]
When adding a file to to your record the first time, that indeed works because the web client sends to the server the base64 content. So everything works great.

However, when you save, the web clients re-reads the binary field content with `bin_size` set to `True`. Therefore, the web client assumes that the content of the field is actually 'xxx bytes'. When the onchange is triggered, the web client sends this value to the server, which will create a 'virtual' record at: https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L5037

Server side, unfortunately, there is no way to know that 'xxx bytes' is not correct value of the field, and that we should re-read it. Client side, on the other hand, it is not acceptable to always read and send the whole content of the binary file (for obvious performance reasons).

At this point, there is no way to have this working without a refactoring on how onchanges work. This might be the case in the future, but not for a stable version.

By the way, what was the use case? I guess printing the content is not the real use case of the problem.

We apologize for the inconvenience.

**Comment by fmdl** [comment]
@nim-odoo I don't understand why but with add `bin_size=False` it the context here it is work : https://github.com/OCA/report-print-send/pull/143

**Comment by nim-odoo** [comment]
@fmdl This method doesn't seem used as an onchange. The problem is with onchanges.

**Comment by fmdl** [comment]
This methode is use during this  onchange : https://github.com/OCA/report-print-send/blob/11.0/printer_zpl2/models/printing_label_zpl2.py#L310

**Comment by nim-odoo** [comment]
I don't know how this module was designed, but one sure thing is that at the moment you should not handle binary fields inside an onchange.
