### ISSUE TITLE
[11.0] odoo.sql_db.Cursor when try to delete SO line

### ISSUE THREAD

**Issue by dansanti** [odoo/odoo#23354]
Impacted versions:
11.0
Steps to reproduce:
1.- Create many SO with at lest 3 lines with no admin user
2.- left a few days
3.- try to delete first line of most older SO with no admin user
Current behavior:
get this error
    File "/usr/lib/python3/dist-packages/odoo/http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 277, in write
    result = super(MailThread, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3021, in write
    self._write(old_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3236, in _write
    self.recompute()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4814, in recompute
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4814, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4672, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 943, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]

KeyError: (<odoo.sql_db.Cursor object at 0x7fac5c18d400>, 6)

Expected behavior:

Video/Screenshot link (optional):

**Comment by dansanti** [comment]
adding a logger just before line 960, i get that :
odoo.api: record: sale.order.line(763,)  field: sale.order.line.currency_id

**Comment by TimLai125** [comment]
@dansanti Hi, do you have any update on this.
As we are encountering the same issue as well i.e. deleting the first order line in the sale.order gives the error message similar to yours. 
In our case, the issue seems to be resolved after some time passes, e.g. no upgrade any modules / restart the server.

**Comment by dansanti** [comment]
Hi, there are not a solution, and yes when you restart server, cache is cleaned and we can delete it, but when in a few days will happends again, till restart odoo

**Comment by TimLai125** [comment]
@dansanti Thank you for the information. I think it is quite troublesome as it seems to be some environment-dependent issue.
@Yenthe666 Can we have anyone that could explain a bit on this?

**Comment by Yenthe666** [comment]
Hmm, this is not an easy one to resolve or figure out exactly what happens. It almost looks like an invalidation / cache issue.
@mart-e have you ever seen something similar?

**Comment by mart-e** [comment]
No, no idea about this. Are you sure there is not an error before that?

**Comment by carlosecv** [comment]
We are experiencing this issue today we try to restart server and see what happen.

**Comment by paudel123** [comment]
Got the same issue.

1. Have more than 2 order/quote lines
2. Want to delete some lines
3. Non admin (but sales manager) user tried to delete line item and have the same issue.

It may be the issue needs to report.

**Comment by dansanti** [comment]
Hello, where are you hosted?, apparently I have this issue with digital ocean host with ubuntu 16.04 and apache proxy settings  @paudel123 @carlosecv  @TimLai125

**Comment by TimLai125** [comment]
We are hosting at Vultr with ubuntu 16.04 and nignx. Furthermore, we have also enabled workers and the database is in a seperate instance.

**Comment by Luckin93** [comment]
I have the same problem! As a response to @dansanti I have my server hosted in my building, Odoo is running with ubuntu 16.04. What do you know about the cache settings?

**Comment by paudel123** [comment]
In my case, it is hosted on Debian 9.4.

**Comment by carlosecv** [comment]
Odoo:	Ubuntu 16.04.2 LTS
                 8GB RAM
PostgreSQL: Ubuntu 16.04.2 LTS
                16 GB RAM

**Comment by SaravananSakthivel** [comment]
File "/home/odoo/workspace/odoo/odoo/models.py", line 3314, in _write
    self.recompute()
  File "/home/odoo/workspace/odoo/odoo/models.py", line 4892, in recompute
    vals = {n: rec[n] for n in ns}
  File "/home/odoo/workspace/odoo/odoo/models.py", line 4892, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/home/odoo/workspace/odoo/odoo/models.py", line 4750, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/workspace/odoo/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/home/odoo/workspace/odoo/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f7dff463cc0>, 9)




Same Error Comming......Once i restart the issue is gone


Any update on this

**Comment by SaravananSakthivel** [comment]
@Yenthe666 Any idea

**Comment by Yenthe666** [comment]
@SaravananSakthivel sorry but way too little info to find the issue for this. Probably a misconfiguration in workers/postgreSQL db

**Comment by mart-e** [comment]
Sorry but we are unable to reproduce this issue ourself. Reposting the same traceback does not help, we need a way to reproduce it to understand the problem.

**Comment by SaravananSakthivel** [comment]
Traceback (most recent call last):
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)  

File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/addons/mail/models/mail_thread.py", line 277, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/addons/mail/models/mail_activity.py", line 335, in write
    return super(MailActivityMixin, self).write(vals)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/models.py", line 3086, in write
    self._write(old_vals)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/models.py", line 3314, in _write
    self.recompute()
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/models.py", line 4892, in recompute
    vals = {n: rec[n] for n in ns}
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/models.py", line 4892, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/models.py", line 4750, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/home/odoo/workspace/odoo-11.0.post20180423/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f7dff463cc0>, 9)



@Yenthe666 @mart-e  this is the full traceback i got as a error......

it keeps changing for users
Ex: 
A user is getting the error like this in sale form
B user is getting the error like this in purchase form

**Comment by pedrobaeza** [comment]
But please put the detailed steps to reproduce the problem (login, go to..., click on..., change this or that, etc).

**Comment by SaravananSakthivel** [comment]
@pedrobaeza  while saving the record not creating.
Ex: 
When i try to adding/removing the value from any text/char/many2one/many2many/one2many field and click on the save button it doesn't work.

**Comment by pedrobaeza** [comment]
This seems a problem with your deployment due to custom modules or custom code. Have you been able to reproduce the problem on runbot (https://runbot.odoo.com with admin/admin)?

**Comment by SaravananSakthivel** [comment]
Not tried

**Comment by mart-e** [comment]
My guess would be for a deployment issue.
Please make sure to follow our recommendations at https://www.odoo.com/documentation/11.0/setup/deploy.html (or the one for the appropriate version)

**Comment by wtaferner** [comment]
@mart-e 
It is a valid issue which does originate and will be solved with an extension of https://github.com/odoo/odoo/pull/26130 (KeyError + MissingError). I am waiting for a review, but I resolved both issues exactly there and it is happening b/c a performance improvement last year removed the ```records.exists()``` filter.

**Comment by dansanti** [comment]
Hi, the only way to reproduce it:
1.- create a sale order with No root user
2.- add some SO lines
3.- left a few days (like 6)
4.- login with no Root user
5.- try to delete a line


I try migrating to another server but problem still happens

then, i try to track the problem, and fails when try to load currency_id

@pedrobaeza the problem is with no admin user, if you try with admin, lines can be deleted but other users can't

**Comment by paudel123** [comment]
Now very upset with the things.

Today again, my customer service representative wanted to delete the first line item but could not.

I logged in as Administrator and delete the line item for him.

Is there anything we can do please...
Is there any patches/fixes for this.

**Comment by TimLai125** [comment]
@paudel123 Hi, the pattern on my customer's environment is slightly different from you, the user is unable to add and delete the order line at the same time, e.g. the user is able to Edit > Delete Line > Save > Edit > Add Line > Save but not Edit > Delete Line & Add Line > Save.
You may ask @wtaferner to send you his patch to fix this, but that is not an official fix.

**Comment by pedrobaeza** [comment]
Thanks all for the info, but it seems there's still no fixed steps to reproduce the problem. @dansanti in your steps, the step 3 is the undetermined, and that's the problem, as we don't know what happen in that "let a few days". It's for sure not a question of time, but something that is done on that time. 

@TimLai125 about your steps, seems to be more reproducible, but are you able to get the error on runbot and specifying exactly the steps done with demo data there?

**Comment by TimLai125** [comment]
@pedrobaeza No, I am not able to reproduce the issue in the runbot but I believe @Yenthe666 is correct that this is actually an issue related to the cache. Therefore it is not easy to reproduce the issue from a clean environment like runbot.
This issue requires someone who is familiar with the Odoo cache mechanism to be able to explain/fix it.

**Comment by Luckin93** [comment]
Does anyone have an update on this?

**Comment by wtaferner** [comment]
@Luckin93 
It is for sure the cache in certain, undefined conditions (sudo related) which is ending up exactly where I am monkey patching as written and demonstrated a possible fix in #26130 . The issue is gone and I did not record any known side-effect so far (with a LOT of computed fields). I furthermore assume that it is related to the ```stock.move.line``` which is often deleted on the fly and newly created by the admin, but this is just a suspicion.

**Comment by Luckin93** [comment]
@wtaferner  Thank You for the response !
I'm going to update my odoo source files hoping that the issue was solved!

**Comment by Luckin93** [comment]
@wtaferner Hello, I'm having the same issue again I don't know what to do! This is the error that a non admin user get. When they try to delete some product line in sale order line. This error happens once or twice a day I don't know what triggers this error.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7fbae114a7f0>, 71)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 924, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 277, in write
    result = super(MailThread, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_automation/models/base_automation.py", line 234, in _write
    _write.origin(records, vals, **kw)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3318, in _write
    self.recompute()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4901, in recompute
    vals = {key: rec[key] for key in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4901, in <dictcomp>
    vals = {key: rec[key] for key in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4754, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7fbae114a7f0>, 71)

**Comment by wtaferner** [comment]
@Luckin93 
You need to use my latest patch in this PR (https://github.com/odoo/odoo/pull/26130/files) and the line 4901 in your traceback does not look like my patch and the latest version of Odoo although I see that you used one version due to ```vals = {key: rec[key] for key in ns}```, but obviously the one without intercepting the ```KeyError```

**Comment by hugho-ad** [comment]
Today I got this error 
![image](https://user-images.githubusercontent.com/10233975/46237899-1b235a80-c34d-11e8-88c0-47fc7f4a7929.png)

Odoo at https://github.com/Odoo/odoo/commit/07cdd24f30c221de96dc1dda452959f9ae358c12
enterprise at https://github.com/odoo/enterprise/commit/7a6cb927ffcaaa9a3d2f0e210972bfb84c3d575d

**Comment by hugho-ad** [comment]
I restarted as suggested in comments above but issue persist

**Comment by Luckin93** [comment]
@hugho-ad I tried the @wtaferner solution that he posted above 9 days ago and I haven't faced the error again.  You should try it.
By the way Thank you very much Wolfgang.

**Comment by thopy** [comment]
I am more on the user side than on the developer side but we had this issue in our company once and our sales people recognized that after trying again after several hours they could safe the record. Something had happen during that time that removed the error. I do not know anything about the Odoo caching system but maybe a kind of cleanup happened that removed the error. 
If so, is there a way to trigger that cleanup?

**Comment by dansanti** [comment]
1.- the only way for reproduce the issue, is creating a sale order, with 2 or more lines, and wait for a few days,
2.- when it happens restarting odoo service can solve the problem

i thinks is a problem with price compute, because adding another currency and change the list price for a old order happens too.

**Comment by ayamemi** [comment]
Hi, i got the same issue for my client. So what should exactly we update to solve this kind of error?
Do i need to update all Odoo Core + Enterprise?

@Luckin93 I saw you do update the code, may i know where?

**Comment by wtaferner** [comment]
@ayamemi 
https://github.com/odoo/odoo/pull/26130 is fixing symptoms but it should be quite safe. I even checked with @rco-odoo in person once...by the way Raphael, did you have time to do the "making the source of evil visible" changes already somewhere?

**Comment by hw-aka** [comment]
Hi, could someone confirm that this is now fixed? I'm on Odoo.sh and no longer see my custom fix function being called since Feb 22, 2019. I'll need to remove the custom fix if this is offically fixed. Thanks.

**Comment by hugho-ad** [comment]
I don't know if is the same error, but it's happening in two of our customer's instances

Error:
Odoo Server Error

Traceback (most recent call last):
 File "/home/odoo/instance/odoo/odoo/fields.py", line 927, in __get__
   value = record.env.cache.get(record, self)
 File "/home/odoo/instance/odoo/odoo/api.py", line 967, in get
   value = self._data[key][field][record._ids[0]]
KeyError: 12996

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/home/odoo/instance/odoo/odoo/http.py", line 651, in _handle_exception
   return super(JsonRequest, self)._handle_exception(exception)
 File "/home/odoo/instance/odoo/odoo/http.py", line 310, in _handle_exception
   raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
 File "/home/odoo/instance/odoo/odoo/tools/pycompat.py", line 87, in reraise
   raise value
 File "/home/odoo/instance/odoo/odoo/http.py", line 693, in dispatch
   result = self._call_function(**self.params)
 File "/home/odoo/instance/odoo/odoo/http.py", line 342, in _call_function
   return checked_call(self.db, *args, **kwargs)
 File "/home/odoo/instance/odoo/odoo/service/model.py", line 97, in wrapper
   return f(dbname, *args, **kwargs)
 File "/home/odoo/instance/odoo/odoo/http.py", line 335, in checked_call
   result = self.endpoint(*a, **kw)
 File "/home/odoo/instance/odoo/odoo/http.py", line 937, in __call__
   return self.method(*args, **kw)
 File "/home/odoo/instance/odoo/odoo/http.py", line 515, in response_wrap
   response = f(*args, **kw)
 File "/home/odoo/instance/odoo/addons/web/controllers/main.py", line 934, in call_kw
   return self._call_kw(model, method, args, kwargs)
 File "/home/odoo/instance/odoo/addons/web/controllers/main.py", line 926, in _call_kw
   return call_kw(request.env[model], method, args, kwargs)
 File "/home/odoo/instance/odoo/odoo/api.py", line 689, in call_kw
   return call_kw_multi(method, model, args, kwargs)
 File "/home/odoo/instance/odoo/odoo/api.py", line 680, in call_kw_multi
   result = method(recs, *args, **kwargs)
 File "/home/odoo/instance/odoo/addons/mail/models/mail_thread.py", line 284, in write

**Comment by Julien00859** [comment]
@hugho-ad it doesn't seem to be the same error

@hw-aka I am not aware we fixed the bug, let me verify

**Comment by hugho-ad** [comment]
@Julien00859 

It's to me, just that I couldn't get the full error log
This part seems to be the same, but a different key value

```python
Traceback (most recent call last):
File "/home/odoo/instance/odoo/odoo/fields.py", line 927, in get
value = record.env.cache.get(record, self)
File "/home/odoo/instance/odoo/odoo/api.py", line 967, in get
value = self._data[key][field][record._ids[0]]
KeyError: 12996
```
```python
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/fields.py", line 937, in get
value = record.env.cache.get(record, self)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7fbae114a7f0>, 71)
```

**Comment by Julien00859** [comment]
Yes, we changed the cache structure around February, the error looks different but it is the same. We didn't find a way to reproduce the bug our side yet...

Our best guess is an invalid cache invalidation on multi-worker when the user discard and re-edit the sale order lines and that both request end up on the same worker. That's by looking at the logs, as I said, we haven't reproduced it in a test environment... Damn you *higgs-bugson*

**Comment by purnendu03** [comment]
I faced this issue on one of my client database. The strange thing is that if i access the same database using different port then i am able to delete the sale order line.

Actual setup is on 8069 port and it's running as service. If i manually run the odoo server and access the database using 8888 port then i can delete sale order line with non admin user.

**Comment by nicomacr** [comment]
We are facing the same issue in some customers. More information:

- the error also appears without using workers (workers=0)
- Most of times it's fixed by a restart but sometimes we have restart the instance and the issue persists 
- We can only replicate with none admin users (it seams working ok with admin)

**Comment by nicomacr** [comment]
opw-2003583
