### ISSUE TITLE
Stock Moves report pivot view has same label (Quantity) for two measures and only one is populated 

### ISSUE THREAD

**Issue by KangOdoo** [odoo/odoo#23507]
Impacted versions: 10

Steps to reproduce: Default view of stock moves

Current behavior:
Two labels for selectable Measures in pivot view. Second one shows no data.

Expected behavior:
Unique labels for each measure

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/36682465/37075522-4fc128bc-2226-11e8-9547-350330f33822.png)

**Comment by Yenthe666** [comment]
@sle-odoo I've just tested this and it is indeed true. There are two fields and one has no data + it screws with the graphs. Can you check please?

**Comment by KangOdoo** [comment]
Hi @Yenthe666 are progress on getting the error in this report looked at?

**Comment by Yenthe666** [comment]
@KangOdoo I made an official ticket for this one as it is in fact confusing. It is no longer the case in v11 though!
OPW 1841097

**Comment by KangOdoo** [comment]
Good morning @Yenthe666 - I'm following this up because @edsersolis earlier today asked me about related issue https://github.com/odoo/odoo/issues/23448 Inventory at Date and Inventory Valuation reports.

IMHO since all of the three Inventory reports in Odoo v10 that have a pivot view have the same mistakes in build could these not all be fixed in one go? I'm sure many users would be grateful

**Comment by Yenthe666** [comment]
@KangOdoo g'morning! I'm assuming they're all related to the same issue, which should be also fixed by OPW 1841097 (but maybe I'm too positive 😆 )

**Comment by KangOdoo** [comment]
@Yenthe666 - what is OPW 1841097?  
I'm hopeful that things are progressing - I see that we're now below 1,000 issues, only 826 to go! ;-)

**Comment by Yenthe666** [comment]
@KangOdoo OPW links to the official Odoo ticket number (which is 1841097 for this bug report).
Things are actually progressing, the counter has dropped a lot in the last months!

**Comment by Yenthe666** [comment]
This is improved for Odoo 10.0 in https://github.com/odoo/odoo/commit/a16114efb43da7a14113b061b2ed0f110b668c74 - it now shows a nice text.
The second field is not always 0.0 and will be set for untracked moves when setting the quantity

**Comment by KangOdoo** [comment]
I am reopening this for following reasons:
1. Label has been changed to 'Quantity done store' which is unclear as what this means
2. Where stock moves have occurred this field still shows zero data
3. My Odoo implementer advises there appears to have only been the change to the label and no other code change
![image](https://user-images.githubusercontent.com/36682465/40399236-91d25f6a-5e7f-11e8-8e07-ddaf9fefc6e2.png)
