### ISSUE TITLE
Odoo.com - Forum corrupt since more than 24 hours

### ISSUE THREAD

**Issue by treviser** [odoo/odoo#24986]
It is not possible to post new questions and most probably many errors more, the forum is unusable.

![selection_055](https://user-images.githubusercontent.com/1814941/40748037-7e38f366-645f-11e8-825c-f312d6520b24.png)

**Comment by pedrobaeza** [comment]
@odony @mart-e can you take a look to this?

**Comment by Yenthe666** [comment]
@JKE-be this is what I pinged you about. It seems to be quite big:
- Not able to comment on (some) topics
- Not able to create a new topic
- Not able to review an item from the queue

**Comment by treviser** [comment]
Meanwhile I'm able to answer questions, but it is not possible to post new questions.

**Comment by JKE-be** [comment]
@treviser 

stange, I cannot reproduce Treviser...
Just created a new one: https://www.odoo.com/forum/help-1/question/pok-134178

**Comment by treviser** [comment]
@JKE-be I have further investigated the issue:
When creating a new tag on a post, the post can not be saved: 403 forbidden, when using existing or no tags, there is no problem.

**Comment by Yenthe666** [comment]
aha, one more to hunt down then. Good catch @treviser 😉

**Comment by JKE-be** [comment]
Tags should be fixed

**Comment by treviser** [comment]
I can not confirm that, it does not work when editing a post.

**Comment by Yenthe666** [comment]
@JKE-be upvotes also don't work by the way.

**Comment by Yenthe666** [comment]
@JKE-be upvoting is still broken. Traceback:

Server application error {"message":"Odoo Server Error","data":{"exception_type":"access_error","message":"Sorry, you are not allowed to create this kind of document. Only users with the following access level are currently allowed to do that:\n- Employees/Employee\n\n(Document model: forum.post.vote)\nNone","name":"odoo.exceptions.AccessError","debug":"Traceback (most recent call last):\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/tools/cache.py\", line 88, in lookup\n    r = d[key]\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/tools/func.py\", line 68, in wrapper\n    return func(self, *args, **kwargs)\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/tools/lru.py\", line 44, in __getitem__\n    a = self.d[obj].me\nKeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f5416105ae8>, 353980, 'forum.post.vote', 'create', True, ('en_US',))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/http.py\", line 650, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/http.py\", line 310, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/http.py\", line 692, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/http.py\", line 342, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/http.py\", line 335, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/http.py\", line 935, in __call__\n    return self.method(*args, **kw)\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/http.py\", line 515, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/odoo/src/odoo/saas-11.2/addons/website_forum/controllers/main.py\", line 427, in post_upvote\n    return post.vote(upvote=upvote)\n  File \"/home/odoo/src/odoo/saas-11.2/addons/website_forum/models/forum.py\", line 699, in vote\n    Vote.create({'post_id': post_id, 'vote': new_vote})\n  File \"/home/odoo/src/odoo/saas-11.2/addons/website_forum/models/forum.py\", line 874, in create\n    vote = super(Vote, self).create(vals)\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/models.py\", line 3260, in create\n    self.check_access_rights('create')\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/models.py\", line 2855, in check_access_rights\n    return self.env['ir.model.access'].check(self._name, operation, raise_exception)\n  File \"<decorator-gen-20>\", line 2, in check\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/tools/cache.py\", line 93, in lookup\n    value = d[key] = self.method(*args, **kwargs)\n  File \"/home/odoo/src/odoo/saas-11.2/odoo/addons/base/models/ir_model.py\", line 1193, in check\n    raise AccessError(msg % msg_params)\nodoo.exceptions.AccessError: ('Sorry, you are not allowed to create this kind of document. Only users with the following access level are currently allowed to do that:\\n- Employees/Employee\\n\\n(Document model: forum.post.vote)', None)\n","arguments":["Sorry, you are not allowed to create this kind of document. Only users with the following access level are currently allowed to do that:\n- Employees/Employee\n\n(Document model: forum.post.vote)",null]},"code":200}

**Comment by treviser** [comment]
By the way downvoting is also broken ;-)
Any news on this?

**Comment by Yenthe666** [comment]
@mart-e I just noticed @JKE-be is on a holiday (enjoy!) for quite a while. Could you please have a look and fix it? Upvoting and downvoting has been broken for almost a month now.

**Comment by mart-e** [comment]
I believe this is handle by the support as @treviser has submitted a ticket about this.
Closing as not a problem on the standard odoo but a deployment issue on one specific odoo instance (our)

**Comment by treviser** [comment]
Yes I did last night while chatting with fhe on the forum ;-)

twanda AG
Ermin Trevisan
Artherstrasse 19
CH-6318 Walchwil
T +41 41 758 1515
M +41 79 208 7373
E trevi@twanda.com
www.twanda.ch
www.ipadweinkarte.twanda.ch

**Comment by rim-odoo** [comment]
Hi guys,

We are working to improve the security of the forum app.
This led to some unwanted side-effects, like temporary disabling the upvote/downvote features.
We are working towards bringing them back soon.

Thank you all for reporting it.

**Comment by Yenthe666** [comment]
Thanks for the update @rim-odoo! Let us know when it is fixed 👍

**Comment by fpodoo** [comment]
Any news on this issue?

**Comment by treviser** [comment]
@fpodoo @rim-odoo It is not fixed yet, even if the status of my ticket is set to "done".

**Comment by Yenthe666** [comment]
It has been broken for 43 days now, that is just sad.
@treviser what was the feedback on the ticket then? It can't be set to done without an answer, right?

**Comment by rim-odoo** [comment]
@treviser It has been reported in an internal task, don't worry. 
@Yenthe666 You may understand there are some things that have a slightly higher priority.

But I can ensure all of you, again, that the forum will eventually be fixed. (It is NOT abandoned.)

**Comment by JKE-be** [comment]
Hello @treviser

Fix is coming today. @rde is working on it now

@yenth FYI initial bug was blocking and make impossible to post a new message. It has been fixed in a few hours...
Now it is not really blocking... but that will be fixed 🤪

**Comment by Yenthe666** [comment]
@rim-odoo and @JKE-be yeah, the really big problem was fixed fast (thanks again).
I do understand that it is not something urgent but upvoting/downvoting on the official forums being down for 43 days does seem very long to me. Don't you agree? I mean it is still an important tool for questions and answers.

**Comment by Yenthe666** [comment]
Oh and happy to see a fix will come today!

**Comment by Yenthe666** [comment]
Hi guys,

@rdeheele has updated the Odoo instance and asked me to test. The upvoting/downvoting and other features seem to work great now.
There is one more issue: converting an answer to a comment gives a 403 and will be checked next week.

Thanks a lot to @rdeodoo and @JKE-be!

Regards,
Yenthe
