### ISSUE TITLE
[v7] after commit 856bc6f on auth_crypt (apply same visibility rules as base), this module hang on install

### ISSUE THREAD

**Issue by hugues-michel** [odoo/odoo#6742]
Hi,

For clean test, I create a new minimal database.
it's impossible to install 'auth_crypt' module after this commit.

Commit link:
https://github.com/odoo/odoo/commit/856bc6f2b147970245f96e26d882f114c32e035c

An extract of log files:
File "/opt/openerp/server/addons/auth_crypt/init.py", line 21, in
import auth_crypt
File "/opt/openerp/server/addons/auth_crypt/auth_crypt.py", line 25, in
openerp.addons.base.res.res_users.USER_PRIVATE_FIELDS.append('password_crypt')
AttributeError: 'module' object has no attribute 'base'

**Comment by chdrsto** [comment]
Hi
Did you solve this issue?
If so, could you share the solution?

**Comment by wtaferner** [comment]
Try this and adapt the code as followed

```python
from openerp.addons.base.res import res_users
res_users.USER_PRIVATE_FIELDS.append('password_crypt')
```

Regards,
Wolfgang

**Comment by chdrsto** [comment]
Hi Wolfgang
It worked. You just saved my day.
Thanks

**Comment by cysnake4713** [comment]
Have the same problem! what caused it?

**Comment by cysnake4713** [comment]
I think this problem is same as #7458, both caused by module import problem, but I can't locate the bug code...

**Comment by cysnake4713** [comment]
>from openerp.addons.base.res import res_users
> res_users.USER_PRIVATE_FIELDS.append('password_crypt')

@wtaferner  the fix code you motioned seems not working for me,  Is  it working for you in commit 880c997 ??

**Comment by chdrsto** [comment]
@cysnake4713 
In the file:
/opt/openerp70/addons/auth_crypt/auth_crypt.py

I had to comment out the line:
#openerp.addons.base.res.res_users.USER_PRIVATE_FIELDS.append('password_crypt')

... and add instead:
from openerp.addons.base.res import res_users
res_users.USER_PRIVATE_FIELDS.append('password_crypt')

**Comment by cysnake4713** [comment]
@chdrsto I have tried this code but sadly still not working, I'm doing this under 880c997, Can you try the code  under this commit? I think this is caused by new module load code

**Comment by cysnake4713** [comment]
@chdrsto @wtaferner @hugues-michel ,
I use virtualenv manage package.
Formerly I update the new code in old virtual environment, I got this issue #6742,
Today I create a new virtual environment, everything is working great, #6742 is not a problem any more,

So I guess this one is caused by some depends or virtualenv problem, not code problem.

Do you use virtualenv like me or maybe some old package is not installed correctly?

**Comment by niecw** [comment]
Hi all,

I also experience the same problem after commit 856bc6f2 when upgrading an existing installation that uses auth_crypt installed.  This is due to the fact that base is not linked under openerp.addons yet in v7.0 (The other installed modules are linked under openerp.addons).  In v8.0 it is.  The fix that Wolfgang (@wtaferner) had provided can resolve the issue.

I haven't tested it with a new database, but looking from the source issue, it would experience the same problem.

**Comment by niecw** [comment]
Tagging @odony as the author of commit 856bc6f.

**Comment by niecw** [comment]
@cysnake4713, commit 880c997 is in 8.0 branch and should not be affected by this error.  The error only affects branch 7.0, IMHO.  The error you experience may be caused by some other source.

**Comment by odony** [comment]
We had never altered the original patch because the issue could not be reproduced in a normal setup. According to the traceback in the description, this can only happen if `auth_crypt` is loaded before `base` is loaded, which is normally impossible because `auth_crypt` *depends* on `base`. It can however be reproduced by explicitly starting the server with `--load=auth_crypt`, even though using this option would make no sense.
The patch of @wtaferner does not hurt and fixes this very rare situation by forcing the import of `base`, so we've just merged it at 52edf789c27a922dec648c49fec259d44a08b42d.
Thanks!

**Comment by niecw** [comment]
Thanks @odony for the prompt response.  In light of searching for the root cause, I continued my investigation guided by @odony's suspicion.  Here are some excerpt of what I've found thus far.
- The command line switches that I use to run Odoo is `--addons-path=addons --xmlrpc-port=8070 -r XXX -w XXX --logfile=/var/log/openerp-server.7.0/openerp-server.7.0.log --log-level=debug`
- `base` has indeed been loaded.  However it is loaded in an earlier group, not together with `auth_crypt`.  Thus, when auth_crypt is being loaded, `base` is listed in the `skip_modules` in the `load_module_graph` method call.  Below is the excerpt of the log during module loading:

>2015-07-29 17:41:20,672 5275 INFO DEMO2 openerp.modules.loading: loading 1 modules...
>2015-07-29 17:41:20,680 5275 DEBUG DEMO2 openerp.modules.loading: module base: loading objects
>2015-07-29 17:41:21,493 5275 DEBUG DEMO2 openerp.modules.loading: Updating graph with 130 more modules
>2015-07-29 17:41:23,443 5275 INFO DEMO2 openerp.modules.loading: loading 115 modules...
>2015-07-29 17:41:23,449 5275 DEBUG DEMO2 openerp.modules.loading: module web: loading objects
>2015-07-29 17:41:23,452 5275 DEBUG DEMO2 openerp.modules.loading: module web_tests: loading objects
>2015-07-29 17:41:23,456 5275 DEBUG DEMO2 openerp.modules.loading: module audittrail: loading objects
>2015-07-29 17:41:23,470 5275 DEBUG DEMO2 openerp.modules.loading: module auth_crypt: loading objects
>2015-07-29 17:41:23,473 5275 CRITICAL DEMO2 openerp.modules.module: Couldn't load module auth_crypt
>2015-07-29 17:41:23,474 5275 CRITICAL DEMO2 openerp.modules.module: 'module' object has no attribute 'base'

- The first group of loading is caused the start of the service which loads all server-wide modules (https://github.com/odoo/odoo/blob/7.0/openerp/service/__init__.py#L84), including `web` module whose `post_load` (https://github.com/odoo/odoo/blob/7.0/addons/web/__openerp__.py#L14) is to `register_wsgi_handler` for `Root()` (https://github.com/odoo/odoo/blob/7.0/addons/web/http.py#L628).  Initiation of `Root()` object calls for `self.load_addons()` (https://github.com/odoo/odoo/blob/7.0/addons/web/http.py#L517).  Still, after this `base` is not listed under `openerp.addons`.  From my tracing, the loading of `base` module is in fact triggered when `crm` module is being loaded, within which `crm_lead.py` imports from `base` (https://github.com/odoo/odoo/blob/7.0/addons/crm/crm_lead.py#L33).
- I've tried to create a new database.  It can be created and used OK but `auth_crypt` cannot be installed due to the same error.
- I've noted that there are a couple of comments in Odoo that mention the same issue:
  - https://github.com/odoo/odoo/blob/7.0/openerp/service/workers.py#L405
  - https://github.com/odoo/odoo/blob/7.0/openerp/service/cron.py#L48

I'm kinda got stuck after this, no idea what to check further.

**Comment by Softdil** [comment]
This sometimes still happens to me when I try to update a complete Odoo or when trying to restore a database in a freshly new downloaded Odoo...

Today I discovered It was happening because in the config file the addon's path was including something like this: '/odoo/addons,/odoo/openerp/addons' and that caused that auth_crypt was trying to load before base.
Changed it to '/odoo/openerp/addons,/odoo/addons' and updated correctly
