### ISSUE TITLE
Mail aliases catch emails from other domains

### ISSUE THREAD

**Issue by luisg123v** [odoo/odoo#69782]
Impacted versions:
- 12.0
- 13.0
- 14.0

Steps to reproduce:
- Configure a mail alias for one model, e.g. support for tickets
- Configure another alias for another model, e.g. crm for leads
- Supposing your domain is yourcompany.com, send an email as follows:
  * To: support@yourcompany.com
  * CC: crm@another-domain-not-owned-by-you.com

Current behavior:
Both a ticket and a lead are created.

Expected behavior:
Since the email's CC is not related to your domain, it should not be considered and the lead should not be created.

The technical reason this is happening is, when checking mail alias candidates, [only usernames are being considered](https://github.com/odoo/odoo/blob/5945806c151b13d9d4cc13aa0a6c96a6b1bbad5f/addons/mail/models/mail_thread.py#L1284), but not domains.

Support ticket number submitted via odoo.com/help (optional):
OPW #2515368

**Comment by pedrobaeza** [comment]
This was already detected by us and fixed in #49656, but I think it was discarded till v14

**Comment by luisg123v** [comment]
@pedrobaeza,

I think the fix  you mention is fixing a different issue. That issue refers to an empty "to", while this one refer to valid aliases but with a different domain.

**Comment by pedrobaeza** [comment]
Sorry, bad link. It's #38484

**Comment by luisg123v** [comment]
@pedrobaeza thanks for the link.

It seems this is not solved yet, not even in 14.0. The `mail.catchall.domain` parameter is not used when loocking matching aliases. Moreover, it seems a first try was done [here](https://github.com/odoo/odoo/blob/020958f55d384e546eb61c98763d45b5db1ed206/addons/mail/models/mail_thread.py#L895), but that variable is declared and never used.

**Comment by pedrobaeza** [comment]
@Yajo @tde-banana-odoo as you were involved in the other PR, can you tell about this?

**Comment by Yajo** [comment]
Oh, this again... 

Long story short:

1. I fixed the bug in https://github.com/odoo/odoo/pull/38459
2. It turns out that bug was being used as a feature by some people out there (such as Odoo S.A.)
3. Odoo reverted it in https://github.com/odoo/odoo/pull/41042, saying they'll maybe fix it some day (https://github.com/odoo/odoo/pull/38459#issuecomment-556038301)
4. @Tecnativa maintains a semi-hidden fix in OCB: https://github.com/OCA/OCB/pull/913 for v11, https://github.com/OCA/OCB/pull/914 for v12, https://github.com/OCA/OCB/pull/944 for v13 and https://github.com/OCA/OCB/pull/1002 for v14.

So, for now, use OCB.

---

Full story: https://github.com/odoo/odoo/issues/39783#issuecomment-627925294

Possible fix for... v15? https://github.com/odoo/odoo/pull/65094

**Comment by tde-banana-odoo** [comment]
> Oh, this again...
> 
> Long story short:
> 
> 1. I fixed the bug in [[FIX] mail: Ignore aliases for other domains #38459](https://github.com/odoo/odoo/pull/38459)
> 2. It turns out that bug was being used as a feature by some people out there (such as Odoo S.A.: [[FIX] mail: Ignore aliases for other domains #38459 (comment)](https://github.com/odoo/odoo/pull/38459#issuecomment-559686521))
> 3. Odoo reverted it in [[FIX] mail: allow backward compatible domain check for aliases #41042](https://github.com/odoo/odoo/pull/41042), saying they'll maybe fix it some day ([[FIX] mail: Ignore aliases for other domains #38459 (comment)](https://github.com/odoo/odoo/pull/38459#issuecomment-556038301))
> 4. @Tecnativa maintains a semi-hidden fix in OCB: [[11.0] mail: ignore alien domain alias OCA/OCB#913](https://github.com/OCA/OCB/pull/913) for v11, [12.0 mail ignore aliases for other domains OCA/OCB#914](https://github.com/OCA/OCB/pull/914) for v12, [13.0 ocb mail ignore aliases for other domains OCA/OCB#944](https://github.com/OCA/OCB/pull/944) for v13 and [14.0 ocb mail ignore aliases for other domains OCA/OCB#1002](https://github.com/OCA/OCB/pull/1002) for v14.
> 
> So, for now, use OCB.
> 
> Full story: [#39783 (comment)](https://github.com/odoo/odoo/issues/39783#issuecomment-627925294)
> 
> Possible fix for... v15? #65094

Simple config param based fix for constraining incoming email domains back at https://github.com/odoo/odoo/pull/115213 (independently from other considerations). It was the "simple fix" that was scrapped a few years ago, back from the dead (globally).
