### ISSUE TITLE
[14] web: issue with readonly attribute on widget toggle_button

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#76183]
Impacted versions: 14

Steps to reproduce: Add readonly="1" where toggle_button is Added
Eg, Time of List/Form view (Field payslip_status)
![Screenshot from 2021-09-09 01-01-34](https://user-images.githubusercontent.com/16624719/132573260-052b3c12-e0e7-4579-adfa-83f3b7e54ebe.png)

Current behavior: Field is clickable and will be Grey/Green on clicking
_(Refreshing Page/Record will display original value)_

Expected behavior: It should not be clickable 
(or Clicking on it should not change Color)

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by msh-odoo** [comment]
@sswapnesh Should be fixed with #57816 maybe I will target branch to 12.0 as it is produced since 12.0

**Comment by Yenthe666** [comment]
@msh-odoo can you please make the PR for V12? :)

**Comment by msh-odoo** [comment]
@Yenthe666 Here is the PR for 12.0: #76426

**Comment by Yenthe666** [comment]
@msh-odoo has fixed this in https://github.com/odoo/odoo/pull/78793 quite a while ago.
I however today figured out it still does not respect this on wizards in Odoo. I've filed OPW `2739468` for this @msh-odoo :)
