### ISSUE TITLE
Livechat Odoo apps and any instance bug)

### ISSUE THREAD

**Issue by shurshilov** [odoo/odoo#85643]
Impacted versions:
14,15

Steps to reproduce:
Go to odoo apps or any odoo instance with live chat
In odoo since some commits change access to partner image, Early it was public now only user auth can see image of partner.
But on livechat not fix it.
Click on odoo livechat and partner icon|image not will be display

Current behavior:
Click on odoo livechat and partner icon|image not will be display
Expected behavior:
image of partner will display.

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/11828278/156343764-143909ca-60ed-4892-8399-e99c07f4d4dc.png)

Support ticket number submitted via odoo.com/help (optional):

**Comment by shurshilov** [comment]
This can also be solved by delete the rule for public user in the line
https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/security/base_security.xml#L26

And in general, it's very strange to assign a public user to the res.partner model for a parent campaign. After all, by default, public user should not have any campaigns because there is no access.
But in the end, I think the solution through python is safer and solves the issue, which is also observed on odoo apps when you chat you don't see a photo of a technical specialist in the presence of this placeholder, which is not very nice.

**Comment by Julien00859** [comment]
Hello @shurshilov, sorry for the delay. I've had a chat about this issue with the team in charge of the module, they know about this bug and don't have a clean solution yet. They plan to dedicate some resources in order to sort this issue. As of saas-15.3 the issue should be partially fixed.

**Comment by mart-e** [comment]
This will be fixed for version 16 in #88238 but in 14.0, you can toggle the Published flag on the partner that is using the livechat to publish his image.
Best

**Comment by shurshilov** [comment]
Well, I've fixed it with my comit for now) do you mean to be public here?
![image](https://user-images.githubusercontent.com/11828278/165345823-99b8b609-bebe-407f-8efc-26ff01cef593.png)
By the way, I also don't understand why partners for a public user include a roll of companies, because a public user doesn't have campaigns, I think the problem is that one line needs to be changed in xml

**Comment by seb-odoo** [comment]
Solved in recent versions.
