### ISSUE TITLE
[9.0] Can't download attachments

### ISSUE THREAD

**Issue by MarkLeemans** [odoo/odoo#8787]
I'm testing Odoo9 and i've installed the Attachment module. Uploading a attachment works fine, but when I try to download an attachment an internal server error (500) occurs. For example:

https://odoo.internal/web/content/609?download=true&t=1443530036375

In the errorlog I get this error:

TypeError: content_common() got an unexpected keyword argument 't'

And when I remove the t argument from the URL I can download the file perfectly fine:

https://odoo.internal/web/content/609?download=true

It occurs in the latest nightly build as well.

**Comment by antonylesuisse** [comment]
@Gorash can you check we dont use t anymore ?

**Comment by Gorash** [comment]
It's already Fixed: d7d433c8c3cbbb79ecfefd377a3fed3bbc8319d1
Thanks for the report

**Comment by MarkLeemans** [comment]
I can't see your commit. Will it be fixed in the latest nightly? Branch 9.0?

**Comment by antonylesuisse** [comment]
I was fixed in community a few days ago and in enterprise just now. Can you check with the latest 9.0 ?

**Comment by MarkLeemans** [comment]
It's not fixed in the latest version downloaded from: http://nightly.odoo.com/master/nightly/deb/ (version Version 10.0alpha1-20150929)

Can I downgrade to RC1?

**Comment by antonylesuisse** [comment]
Are you sure you are up to date check the content of the file

addons/web/static/src/js/widgets/sidebar.js

Line 184 check for &t=' + (new Date().getTime()); if it's there you probably are not up to date.

It should be like this

https://github.com/odoo/odoo/blob/9.0/addons/web/static/src/js/widgets/sidebar.js#L182

**Comment by MarkLeemans** [comment]
When downloading the latest nightly deb from the repository it's still not fixed.. I've fixed this manual now and that works.
