### ISSUE TITLE
Odoo Seo Friendly URL for sites

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo#9774]
Hi all,

Are there any module in Odoo or OCA which provides the functionality of changing URLs?

Thanks
regards

From: @lisandi

> Probably you could address a seo friendly url for sites to i.e. without that /page/ or with a definable /slides , /blog etc path segment, which is multilingual to.

https://github.com/odoo/odoo/issues/9745#issuecomment-159885137

**Comment by lukebranch** [comment]
@rafaelbn ,

check out the ..._seo modules here:

https://github.com/blooparksystems/website/tree/8.0/

@jholze will be able to fill you in on the details.

**Comment by jholze** [comment]
Hi @rafaelbn,

we are working on a SEO Suite for odoo which will be released soon and also available in the OCA Repo. https://github.com/blooparksystems/website/tree/9.0

**Comment by jholze** [comment]
I will make a video of the current state tomorrow.

**Comment by rafaelbn** [comment]
We we analyzing this modules too:

- https://github.com/treytux/odoo-website/tree/master/website_blog_url_friendly
- https://github.com/treytux/odoo-website/tree/master/website_sale_url_friendly
- https://github.com/treytux/odoo-website/tree/master/website_url_friendly

cc @antespi @Yajo @pedrobaeza @sergio-incaser @carlos-incaser

**Comment by rafaelbn** [comment]
Sorry I forgot this one:

- https://github.com/treytux/odoo-website/tree/master/website_seo

Thanks @jholze @lukebranch !!!

**Comment by lisandi** [comment]
Thanks Jens

Is it working in multilingual sites and enabeleing language/region specific
seo entries?




With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

 *ANDI BECKER*

CEO/General Manager LisAndi Co., Ltd.

*about.me/andibecker
<http://about.me/andibecker>--------------------------------------------------*
*LisAndi Co. Ltd.*, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk/Facetime/eMail:  andi@lisandi.com

--------------------------------------------------
This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by jholze** [comment]
Hi @lisandi,

yes it is. You can have urls like

domain.com/suppliers (default langauge) 
domain.com/de/lieferanten (eg. german localisation) 

the lang short code is set and can be defined for all languages in the language model.

regards,

Jens

**Comment by collex100** [comment]
Guys, help me in this matter. These modules do not work properly.
https://github.com/treytux/odoo-website/tree/master/website_blog_url_friendly
https://github.com/treytux/odoo-website/tree/master/website_sale_url_friendly
https://github.com/treytux/odoo-website/tree/master/website_url_friendly

In these modules after installation, I can not change the field:
_Add keyword
Title
Description_

Works only field:
_Slug_ 

In this module: 
https://github.com/blooparksystems/website/tree/8.0/
then change the value of the field _Slug_ , my page is not available at the new address. And the old works.

I work site, blog, shop modules. What's happening? As these modules work with you?

Thanks if will respond and share your experience!

**Comment by pedrobaeza** [comment]
Try https://github.com/OCA/website/tree/8.0/website_seo_redirection

**Comment by collex100** [comment]
Thank you! Pages become seo. But on the page references are old. So the search engine bot can not find SEO page. He sees the old links. This solution, but by half. If there is some experience, I will be happy if you share! Thank you!

**Comment by Yajo** [comment]
This is not the place for those bugs, please submit them on their respective repositories.

**Comment by rafaelbn** [comment]
Solved.

**Comment by collex100** [comment]
I'm sorry but that solved? 
All three modules have a problem, tell me where you can discuss it? After all, someone use these solutions. Tell me how you decide your issue, please.

**Comment by pedrobaeza** [comment]
You have to put the issues in the corresponding repo: https://github.com/treytux/odoo-website/issues/new

**Comment by rafaelbn** [comment]
This issue is for Odoo. In the OCA module we did is solved this issue.

Furthermore:

The main debate about this is: https://github.com/odoo/odoo/issues/12527

**Comment by rafaelbn** [comment]
Ok, reopen as this is a Wishlist referenced.

**Comment by collex100** [comment]
A lot thanks!

**Comment by 3sPoojanath** [comment]
@jholze 
Can you share a video or guide for your module? I have installed it but not sure how to get it to work with separate URLs for each language

**Comment by jholze** [comment]
@Shiraj-Nisus still not. We have some points in a current sprint. Maybe i can deliver some things later in the docs.

**Comment by jholze** [comment]
Just a quick note, we changed our development to use the oca addon to manage page redirections as our base. We decided this, because the core works really nice and we want to use our time to extend this. Even it works out of the box with all controller and our concept was a bit limited so far. We are still working on some improvements for the website editor to manage the redirection in the website builder, because the backend views are not very user friendly. More coming soon ...

**Comment by rafaelbn** [comment]
I'm closing this issue as the question was:

> Are there any module in Odoo or OCA which provides the functionality of changing URLs?

And the answer was:

Try https://github.com/OCA/website/tree/8.0/website_seo_redirection

If any other issue please open a new one with the correct topic! 😄

**Comment by crazyshark2** [comment]
can anyone know for version 16 seo url
